### ISSUE TITLE
建议出UTF-8编码版

### ISSUE THREAD

**Issue by LiarOnce** [printempw/blessing-skin-server#1]
如题，强烈要求出UTF-8编码，GBK编码经常乱码

**Comment by prinsss** [comment]
咦咦咦？我记得我一直都是utf-8的文件编码啊！

**Comment by joyqat** [comment]
说的是数据库吧。
创建数据库表的字符集默认是latin1.  文件是install.php。这直接导致了不能使用中文用户名。

修改试验成功的配置（用于支持中文用户名）是将默认建立的数据库表的字符集改为utf8(install.php)，然后在用户名合法检查的正则表达式中加入中文字符\x{4e00}-\x{9fa5}  (文件是User.class.php)

表示我的服务器上有一大票小伙伴都用的中文名欸~不支持中文用户名很头疼的。
另外，有些VPS 默认的PHP 环境中禁用了 scandir函数，导致仪表盘里不能统计材质的数量，建议在安装时提醒用户~或者换一种统计材质数量的方法~ 

讲道理必须给好评！方案很漂亮！

**Comment by prinsss** [comment]
原来如此
我还以为没人用中文id呢，建表的时候就没加 set utf-8（扶额
确实是我的疏忽，周末就会更新
那我改用 readdir 来统计好了，这个应该不会被禁吧

**Comment by prinsss** [comment]
啊啊，另外问下你有没有想要在仪表盘里加入的功能？感觉太少了呢
现在打算把配置用数据表储存（各种杂七杂八的配置越来越多了），然后再仪表盘更改配置

**Comment by joyqat** [comment]
赞赞赞
大概可以在用户管理界面查看这个用户的模型预览和材质占用空间的统计

**Comment by prinsss** [comment]
不错呢。
把用户管理页里一些不常用的配置放到新的 showUser 页面去好了，顺带在上面加上 3D 预览和一些用户的详细信息

**Comment by joyqat** [comment]
虽然有点过分，但还是想说，能加入简单的皮肤编辑功能就更好了~
参见skinnr这个repo

**Comment by prinsss** [comment]
没必要。这不应该是皮肤站的工作，而且功能也不及 MCSkin 3D 这类程序强大，加进去不过是徒增臃肿

**Comment by LiarOnce** [comment]
不，我用Openshift建一片乱码，然后去看了index.php，是ASCII的

**Comment by LiarOnce** [comment]
现在自己把程序全部改成UTF-8编码情况才好了点

**Comment by prinsss** [comment]
诶哟woc，sublime 的 ConvertToUTF-8 咋不管事了
确实是我的疏忽，已记录

**Comment by prinsss** [comment]
呃，我回去看了一下，所有的文件全都是 UTF-8 without BOM 编码啊？
你是在哪里下载的源码？

**Comment by LiarOnce** [comment]
就是GitHub下的，get.php和include下全部php程序都是ASCII编码

**Comment by LiarOnce** [comment]
也不知道为什么会这样了

**Comment by prinsss** [comment]
唔，明明本地都是 UTF-8 的。。
难道是 Git 的锅？

**Comment by xfl03** [comment]
中文用户名感觉不应该支持，建议作者加入正则表达式将用户名限制在mojang官方许可的范围

**Comment by prinsss** [comment]
说的也是啊，如果有需求的话就自己改吧 ( ´д`)
