### ISSUE TITLE
这个提示是为什么？

### ISSUE THREAD

**Issue by liushiqi** [printempw/blessing-skin-server#100]
错误码：1049

详细信息：无法连接至 MySQL 服务器，请检查你的配置。服务器返回的信息： Unknown database 'blessing-skin'

mysql:5.7.20
php:7.0.22

**Comment by prinsss** [comment]
你是不是没有在 `.env` 中正确配置你的数据库连接信息？我看你报错里还是默认的数据库名。

我相信你不会不知道 MySQL 数据库是什么的。

**Comment by liushiqi** [comment]
谢谢，sql 数据库名称是不是不能有-字符
