### ISSUE TITLE
3.3.x版本点击“Blessing Skin Server”超链接时，页面显示不正常

### ISSUE THREAD

**Issue by z1252583957** [printempw/blessing-skin-server#101]
3.3.x版本点击“Blessing Skin Server”超链接时，css与js无法正确加载，页面不正常显示。（此时地址栏的地址是http://127.0.0.1/index.php）

可能用的是相对路径，静态资源的路径加了index.php，导致404访问不到。
例如：
实际请求地址是（404）：http://127.0.0.1/index.php/resources/assets/dist/css/style.css?v=3.3.1

我把项目文件夹中：.htaccess文件中的"Order allow,deny”、”Deny from all”内容去掉了，原因是apache2.4已经不支持这两个命令，不知道是不是这个原因所致。

运行环境：
操作系统：windows
PHP版本：7
apache版本:2.4

**Comment by g-plane** [comment]
为什么要加 `index.php` 呢？

**Comment by z1252583957** [comment]
点这个超链接就会自动加

**Comment by g-plane** [comment]
你就不能直接访问 http://127.0.0.1/ 吗？

**Comment by z1252583957** [comment]
我直接访问的 http://127.0.0.1/是正常的，点了一下“首页”也是正常的，但点“Blessing Skin Server”就不正常了。我去示例网站上试了试，没有这个问题。这是3.3.X版本问题还是我的配置有问题？

**Comment by prinsss** [comment]
检查一下你『管理后台 -> 站点配置 -> 站点地址（URL）』的配置值里面有没有包含 `index.php`？

**Comment by g-plane** [comment]
我刚刚测试了，带有就会出错。

**Comment by prinsss** [comment]
话说 Apache 新版不支持那些命令了啊，因为我一直用的 Nginx 所以没注意到，感谢指出👍

**Comment by z1252583957** [comment]
哦，站点地址的确带了php，去掉了，现在已解决，十分感谢

**Comment by g-plane** [comment]
还好，能用：
![image](https://user-images.githubusercontent.com/17216317/32329962-7cad7656-c019-11e7-8662-286e89b885b0.png)

**Comment by prinsss** [comment]
更新了一下 `.htaccess`，看起来好看点了，在 Apache v2.4.18 上测试通过。https://github.com/printempw/blessing-skin-server/commit/e3a74d402fbb799c4ce04f39a80f2eff8ecd4212
