### ISSUE TITLE
【bug反馈】皮肤上传者无法删除上传的皮肤

### ISSUE THREAD

**Issue by suoyukii** [printempw/blessing-skin-server#104]
这是那个我上传后删除不了的皮肤
[https://skin.prinzeugen.net/skinlib/show/10456](https://skin.prinzeugen.net/skinlib/show/10456)

**Comment by suoyukii** [comment]
皮肤设置为私有也出现了问题

**Comment by prinsss** [comment]
你能删除上传的其他皮肤么？

**Comment by suoyukii** [comment]
![qq 20171107164508](https://user-images.githubusercontent.com/16282726/32484542-2b2e03c0-c3db-11e7-9714-1e3b2e585199.png)

**Comment by suoyukii** [comment]
@printempw 如上图，删除的时候系统错误代码500

**Comment by suoyukii** [comment]
![qq 20171107164912](https://user-images.githubusercontent.com/16282726/32484651-9da3bd8c-c3db-11e7-81de-567195091e38.png)

**Comment by suoyukii** [comment]
其他的皮肤也一样不能设置私有和删除

**Comment by prinsss** [comment]
问题已经定位，请等待修复。

**Comment by prinsss** [comment]
问题已修复，请等待新版本更新。
