### ISSUE TITLE
【BUG反馈】材质无法删除，设为隐私，修改名称

### ISSUE THREAD

**Issue by tjsky** [printempw/blessing-skin-server#105]
我开始以为是自己部署的问题，后来发现演示站也是同样的问题。
点击【设为隐私】后就这个样子
![](http://ww1.sinaimg.cn/large/7dd4b1bbly1fm74cmxvy4j20dz04qdfx.jpg)

点【修改名称】就这样。
![](http://ww3.sinaimg.cn/large/7dd4b1bbly1fm74er3juij20hz042747.jpg)

系统win7SP1 浏览器火狐51.0

看了下貌似点击后，JS并没有被执行，浏览器没有任何流量被送出，直接错误了。

**Comment by prinsss** [comment]
不应该啊，你换个浏览器试试？

**Comment by dz-paji** [comment]
![image](https://user-images.githubusercontent.com/19299425/33656197-426ed096-dab0-11e7-88a1-8d559ebd6313.png)
并没有任何问题哦

**Comment by g-plane** [comment]
估计这是火狐的锅。已经修复了，请耐心等待更新。

**Comment by tjsky** [comment]
@ZhangqianStudio 我测试在我的系统环境下IE11，IE8、Firefox下都有这个问题，只有chrome下能正常。

**Comment by g-plane** [comment]
IE8 太旧了，不会去做支持的

**Comment by tjsky** [comment]
肯定不用支持IE8了，还用IE8的人还是别上网了。。

我只是说下我测试情况，

作者大大们能搞定IE11和Firefox就行。

**Comment by g-plane** [comment]
Firefox 的问题在你提这个 issue 之前就已经被修复，只是未发布新版本。
IE11 我稍后会测试。

**Comment by g-plane** [comment]
已测试，Windows 10 1709 下的 IE11 没有出现像 Firefox 这样的问题，但皮肤库和衣柜不能正常显示。已修复（技术细节见 commit message：https://github.com/printempw/blessing-skin-server/commit/bd32fc51a7a5fd7b19890bd83a96fad0d7e1e318 ）。
最后感谢反馈。
