### ISSUE TITLE
关于Alex模型的一点小bug

### ISSUE THREAD

**Issue by NekoLemon** [printempw/blessing-skin-server#106]
皮肤为Alex模型或者角色选择Alex模型的情况下，预览界面的模型仍然是Steve导致皮肤在预览界面出现黑边/白边，当然游戏里面是正常的，但就是很不爽。明天下午我看看源码是怎么写的。。。

**Comment by prinsss** [comment]
正常，因为本项目目前使用的 3D 皮肤预览库不支持 Alex 模型的皮肤预览😕

本来之前有计划更换其他预览库的，不过备选的 3D 预览库都有着一些缺陷，所以最后还是维持原样了。

如果你有意愿，欢迎贡献代码🤗

**Comment by g-plane** [comment]
突然发现其实是有两处都没有支持 Alex 模型，一个 3D 预览，另一个是皮肤库列表中的平面预览。

**Comment by prinsss** [comment]
被你发现了（x

这个也是因为找不到合适的预览库

**Comment by g-plane** [comment]
![image](https://user-images.githubusercontent.com/17216317/34527144-9da68f36-f0df-11e7-87c2-07b45382d8c0.png)
![image](https://user-images.githubusercontent.com/17216317/34527163-a70b893c-f0df-11e7-8e2d-99a9b191399d.png)
![image](https://user-images.githubusercontent.com/17216317/34527854-ea3a313e-f0e1-11e7-84cb-87753c162895.png)
第一张图感觉跟游戏有点出入，不过它是用工具进行单双层转换过来的；
第二、三张基本没什么问题。

**Comment by prinsss** [comment]
新版本（ https://github.com/printempw/blessing-skin-server/commit/e477059eb8f766f9a2576230f7670c14f62eba57 ）中已经修复这个问题，现已支持 Alex 模型与双层皮肤预览，敬请期待。

![Snipaste_2018-02-24_16-15-45.png](https://i.loli.net/2018/02/24/5a911f3c7f130.png)
