### ISSUE TITLE
[新]第三方CDN

### ISSUE THREAD

**Issue by dz-paji** [printempw/blessing-skin-server#109]
https://resources.zqstudio.top/

**Comment by prinsss** [comment]
需要添加介绍 ~~（广告）~~ 之类的文字吗？

**Comment by dz-paji** [comment]
不需要

Sent from HonokaMail by HonokaClub

On 8 Feb 2018, at 4:02 PM, 621sama <notifications@github.com<mailto:notifications@github.com>> wrote:


需要添加介绍 （广告） 之类的文字吗？

**Comment by prinsss** [comment]
OK，[已添加](https://github.com/printempw/blessing-skin-server/wiki/%E7%9A%AE%E8%82%A4%E7%AB%99-CDN-%E9%85%8D%E7%BD%AE)。
