### ISSUE TITLE
缺少Authme-reload数据库中“realname”列的值

### ISSUE THREAD

**Issue by yeyifangg** [printempw/blessing-skin-server#11]
Authme-reload才使用了$SHA$Salt$Hash的格式
但是Authme-reload的数据库里有一列叫做realname啊……

**Comment by yeyifangg** [comment]
所有问题均已自行修复

**Comment by prinsss** [comment]
我记得 realname 是大小写正确的用户名吧，把 数据对接用户名字段 填 realname 就可以了吧？

**Comment by yeyifangg** [comment]
不行的，有username和realname两个字段，都是not null

**Comment by prinsss** [comment]
这样啊，因为别人提供给我的 authme 数据表没有 realname 字段 。。
什么版本的 authme 有 realname 字段呢？
