### ISSUE TITLE
PHP 7.2下無法進入管理員面板

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [printempw/blessing-skin-server#110]
## 出錯信息
```
count(): Parameter must be an array or an object that implements Countable (View: /var/www/html/skin/resources/views/admin/index.tpl)
```

## 出錯位置
`<程序根目錄>/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php`
```
L1185: $originalWhereCount = count($query->wheres);
```

## 復現方法
嘗試進入管理員面板，可能其他頁面都有這個問題

## 使用環境
* Arch Linux
* Nginx 1.12.2
* PHP 7.2.2
* MariaDB 10.1.30
* Blessing Skin Server 3.3.2

## 相關issues
* https://www.google.com/search?q=php+count+Parameter+must+be+an+array+or+an+object+that+implements+Countable
* yiisoft/yii#4167
* Automattic/jetpack#8420

**Comment by dz-paji** [comment]
程序不支持php7.2
请静待v4版本

**Comment by prinsss** [comment]
是的，目前 Blessing Skin 还未支持 PHP 7.2（因为本程序底层的 Laravel 5.2 尚未也不会适配 PHP 7.2 的 `Countable` 接口变化）。

大概在明天我会释出一个补丁包，以期解决 Blessing Skin 目前版本在 PHP 7.2 上无法运行的问题。

**Comment by WUGqnwvMQPzl** [comment]
如果現在的版本不支持PHP 7.2，爲何README那邊沒有說明
> PHP >= 5.5.9 （如果服务器不支持，你可以用 v2.x 版本）

等待補丁包發佈

**Comment by prinsss** [comment]
因为 PHP 7.2 发布、我知道这个 breaking change 的时候我人还在外地上学，不方便更新 README。事实上我今天刚刚回到家，所以明天会尽快释出补丁包 :-)

**Comment by prinsss** [comment]
![test screenshot](https://i.loli.net/2018/02/09/5a7c9fe2e08a2.png)

补丁包传到 Dropbox 上了，解压了把 `vendor` 拖到程序根目录覆盖过去就 OK：

https://www.dropbox.com/s/r1x2ijbozxd0p7y/bsv3_php72_patch_180209.zip?dl=0

**Comment by WUGqnwvMQPzl** [comment]
問題已解決，多謝
