### ISSUE TITLE
[讨论]关于皮肤站的普通用户无权查看他人上传的私密材质的错误页面的标题上的 HTTP Response Code

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#111]
如题，不想再打一遍字了（
![tim 20180210120050](https://user-images.githubusercontent.com/16630630/36058404-237b5ba4-0e5a-11e8-80b7-d23cd9fbc7b3.png)
我觉得这个地方改成 403 Forbidden 更好些？

**Comment by xfl03** [comment]
同样感觉403比404在这个问题上更加合适

**Comment by prinsss** [comment]
已改进，感谢建议。

其实你可以也直接提个 PR 的 😉
