### ISSUE TITLE
==

### ISSUE THREAD

**Issue by rainyorange** [printempw/blessing-skin-server#112]
## The Problem 问题描述

找回密码时，发送验证邮件时出错，提示"邮件发送失败，详细信息：Connection could not be established with host smtp.zoho.com [Connection timed out #110]"

## Environment 运行环境

请填写以下内容 / Please tell us about your environment.

/
/
/
/
/
360极速浏览器，https://skin.prinzeugen.net/auth/forgot

## Error Message 错误信息

提示"邮件发送失败，详细信息：Connection could not be established with host smtp.zoho.com [Connection timed out #110]"

## Steps to Reproduce 重现步骤

输入邮箱，输入验证码，点击发送。

## Attachments 附件

如果有需要，请在这里附上你的日志文件（如果日志很长，请上传至某处并提供链接）/ Attach your log file here if necessary.

**Comment by rainyorange** [comment]
我觉得邮箱服务器炸了，，都怪我忘了密码==

**Comment by prinsss** [comment]
演示站的密码重置服务应该已经恢复，你可以尝试重置密码了。
