### ISSUE TITLE
用户头像与材质预览出现404

### ISSUE THREAD

**Issue by KatyushaScarlet** [printempw/blessing-skin-server#113]
## The Problem 问题描述

已上传材质并手动设置头像，但头像与材质预览出现404（详见截图附件）
服务端文件权限已设置正确（www用户）

## Environment 运行环境

请填写以下内容 / Please tell us about your environment.

- Blessing Skin 版本 / version of Blessing Skin

v3.4.0

- 虚拟主机还是 VPS / virtual hosting or VPS

VPS

- PHP 版本 / version of PHP

7.1.7

- 什么 Web 服务器，Apache 还是 Nginx / which web server and its version

nginx/1.12.2

- 什么浏览器，出现错误时的地址栏 URL 是什么 / which browser and URL

Chrome 64.0.3282.140 （正式版本）（64位）

https://mc.katyusha.top/user/closet

https://mc.katyusha.top/avatar/128/S2F0eXVzaGFTY2FybGV0QE91dGxvb2suY29t.png?tid=1
https://mc.katyusha.top/preview/1.png

## Error Message 错误信息

Request Method:GET
Status Code:404 

出现错误时的提示，请把它贴上来（截图或文本）/ Paste the error message or a screenshot here.

## Steps to Reproduce 重现步骤

无，始终为404错误

## Attachments 附件

![20180228225850](https://user-images.githubusercontent.com/24467495/36794582-b1197d26-1cdb-11e8-8e5b-50d41a796073.png)
![20180228225906](https://user-images.githubusercontent.com/24467495/36794588-b6d8cda2-1cdb-11e8-8014-adf24f942d5a.png)

**Comment by prinsss** [comment]
看看「常见问题」中的这一项这是不是符合你的情况？

https://github.com/printempw/blessing-skin-server/wiki/FAQ#%E5%8F%AA%E6%9C%89%E5%9B%BE%E7%89%87%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E5%85%B6%E4%BB%96%E9%83%BD%E6%AD%A3%E5%B8%B8

**Comment by KatyushaScarlet** [comment]
抱歉我忽略了，正在检查 :)

**Comment by KatyushaScarlet** [comment]
果然忘记删掉，感谢您的回复

**Comment by prinsss** [comment]
祝你使用愉快 ;)
