### ISSUE TITLE
输入内容的多语言支持

### ISSUE THREAD

**Issue by dz-paji** [printempw/blessing-skin-server#115]
![image](https://user-images.githubusercontent.com/19299425/37498179-cf129754-28f7-11e8-90e6-cd16b8ab09de.png)
RT.
在这种情况下，感觉中文公告和中文banner很违和

**Comment by prinsss** [comment]
确实如此。

不过我近期内是无法为 BS 添加此功能了，所以，欢迎各位 PR。

此功能也可以通过编写插件实现，实现方式大概有两种：一是劫持 `user.index` 视图，二是根据当前 locale 在运行时修改 `options.announcement` 的值（首页的 description 同理）。
