### ISSUE TITLE
无法获取玩家皮肤Json信息 & 插件管理列表无法加载

### ISSUE THREAD

**Issue by Lostpart** [printempw/blessing-skin-server#116]
## The Problem 问题描述

尝试获取用户皮肤的json的时候，会产生报错

## Environment 运行环境

- v3.4.0
- VPS
- 5.5.12
- Apache
- Chrome 63.0.3239.132 http://skin.mcmhxk.com/yosoro.json

## Error Message 错误信息

Undefined property: App\Events\CheckPlayerExists::$player_name

## Steps to Reproduce 重现步骤

只要获取，就会产生报错

## Attachments 附件

<details>

[2018-03-18 03:50:11] production.ERROR: exception 'ErrorException' with message 'Undefined property: App\Events\CheckPlayerExists::$player_name' in C:\wamp\www\plugins\bs-super-cache\src\Listener\CachePlayerExists.php:28
Stack trace:
#0 C:\wamp\www\plugins\bs-super-cache\src\Listener\CachePlayerExists.php(28): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', 'C:\\wamp\\www\\plu...', 28, Array)
#1 [internal function]: SuperCache\Listener\CachePlayerExists->cachePlayerExists(Object(App\Events\CheckPlayerExists))
#2 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(221): call_user_func_array(Array, Array)
#3 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(419): Illuminate\Events\Dispatcher->fire(Object(App\Events\CheckPlayerExists), Array, false)
#4 C:\wamp\www\app\Http\Middleware\CheckPlayerExist.php(32): event(Object(App\Events\CheckPlayerExists))
#5 [internal function]: App\Http\Middleware\CheckPlayerExist->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Routing\Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#13 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#16 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\wamp\www\app\Http\Middleware\DetectLanguagePrefer.php(12): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: App\Http\Middleware\DetectLanguagePrefer->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 C:\wamp\www\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#31 C:\wamp\www\bootstrap\kernel.php(20): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#32 C:\wamp\www\index.php(30): require('C:\\wamp\\www\\boo...')
#33 {main}  

</details>

———————————————

以及一个疑难杂症向的报错
插件市场/插件管理界面无限“处理中...” 无提示/错误日志
打开插件管理界面就会无限加载，然后就没然后了
不知道是否有处理方法

**Comment by prinsss** [comment]
升级你的 **所有** 插件到最新版，谢谢。

你目前导致出现问题的是 BS Super Cache 这个插件，请升级它至最新版。

为什么我在升级提示里讲了那么多遍升级插件还是会有人看不见……

**Comment by Lostpart** [comment]
我不是在为自己开脱但是我大概知道为啥我会遇到这个问题了，因为……就如同我在文章末尾所报告的第二个问题一样，插件市场和管理界面打不开（我确定我升级了插件市场）但是后面折腾插件市场导致我忘记手动升级其它插件了。感谢作者的回复

**Comment by Lostpart** [comment]
我在挂了足够久以后好像弹出了一个神奇的提示，直接发在这个issue里吧，就不开新issue了
DataTables warning: table id=plugin-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
不知作者是否有处理办法

**Comment by g-plane** [comment]
「插件管理」和「插件市场」两个是不同的。如果是与「插件市场」有关的问题，请到 https://github.com/bs-community/unofficial-plugins-market 开 issue 或直接邮件联系我。

**Comment by g-plane** [comment]
@printempw 3.4.0 是不是还是使用 DataTables？

**Comment by tnqzh123** [comment]
建议在 FAQ 中加一条「使用 CDN 的用户请关闭 CDN 后再试一次」
目前发现大部分这类问题在直连后就能解决

**Comment by Lostpart** [comment]
与群内其它群员研究后排查出可能是腾讯云CDN的锅，具体原因还在研究中

**Comment by prinsss** [comment]
@g-plane 是的，只是将其版本升级了一下

**Comment by prinsss** [comment]
@Lostpart 这个错误提示里没什么有用的信息。

最好是按 F12 打开开发者工具，刷新页面后再查看控制台以及 network 选项卡中是否有奇怪的错误。

**Comment by tnqzh123** [comment]
@printempw 在群里讨论过了，HTTP Resopsne Code 是 567，一个连文档都没有记载的腾讯云 CDN 的神秘响应码
我以前开工单问过，好像是说回源错误来着？

**Comment by Lostpart** [comment]
@printempw 
打开后会在访问http://(域名)/admin/plugins/data?(参数省略见下方)  刚好1分钟后产生567错误
直接访问http://(域名)/admin/plugins/data 是没问题且可以访问的

直接访问源站无上述问题出现

被省略的参数的完整版
<details>
http://(域名)/admin/plugins/data?draw=1&columns%5B0%5D%5Bdata%5D=title&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=description&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=author&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=version&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=status&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=operations&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=false&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=25&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1521336112654
</details>

**Comment by prinsss** [comment]
好奇妙。

开启 CDN 的情况下，直接访问 `http://(域名)/admin/plugins/data/那一大串参数` （GET 或 POST）正常吗？

**Comment by Lostpart** [comment]
@printempw
Get和Post好像都不正常（然而我也不确定正常是什么样的）
我直接把域名给你吧
（已移除）

**Comment by prinsss** [comment]
@Lostpart 你给我也没啥用啊，我又没权限访问你的 /admin。而且我现在手头也没电脑，没法排查问题。

初步推测可能是 URL 太长导致腾讯云 CDN 请求源站时出现了问题。因为我直接访问 `你的首页 + 那一大串参数` 时也会 timeout。

**Comment by g-plane** [comment]
![image](https://user-images.githubusercontent.com/17216317/37561890-5af2bd0a-2a95-11e8-81a4-185a418845ce.png)
这下应该可以

**Comment by Lostpart** [comment]
这个报错的错误看起来很高级【笑

**Comment by g-plane** [comment]
https://github.com/g-plane/blessing-skin-server/commit/76b762a48e9a717489b14d5ea52ff4c6c218d235

**Comment by EDLDDD** [comment]
@printempw 我和LZ遇到了一样的问题，开启腾讯云CDN后在后台管理也会出现那个提示

**Comment by g-plane** [comment]
所以你应该试试把那条 URL 加入 CDN 排除规则看看？

**Comment by Lostpart** [comment]
@EDLDDD 把整个目录的缓存时间设成0秒就行了

**Comment by EDLDDD** [comment]
@Lostpart 不行，我将整个admin目录设计为0秒，还是弹出了那个提示
