### ISSUE TITLE
CDN for worldwide.

### ISSUE THREAD

**Issue by dz-paji** [printempw/blessing-skin-server#117]
```
 https://bs.honokacloud.com
```
It's the worldwide CDN for blessing skin. Could also be used in Mainland China sites if you want.
Wish you will add it to wiki :)

**Comment by prinsss** [comment]
Awesome! Thanks for your contribution. 😉

And, would you like to add a short description for the CDN service? (sponsorship, advertisement or something)

**Comment by dz-paji** [comment]
All right.
If it's possible, I shall add this:

> This site is hosted by HonokaCloud. If you wish to donate for me, you can [Buy me a coffee](buymeacoff.ee/dzpaji)

**Comment by xfl03** [comment]
@ZhangqianStudio Maybe a wrong link address for **Buy me a coffee**. Please give an attention.

**Comment by prinsss** [comment]
Yes, it's actually https://buymeacoff.ee/dzpaji . GitHub just transformed the hyperlink without scheme wrongly.

**Comment by prinsss** [comment]
The wiki page was updated.

https://github.com/printempw/blessing-skin-server/wiki/%E7%9A%AE%E8%82%A4%E7%AB%99-CDN-%E9%85%8D%E7%BD%AE

**Comment by dz-paji** [comment]
Well, thanks a lot :)
