### ISSUE TITLE
积分说明中的错误

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#118]
在设置收藏皮肤库中的材质需要消耗的积分数后，点击用户中心首页的积分出现的提示中仍显示“添加皮肤库里的材质到衣柜不消耗积分”。
![tim 20180627213845](https://user-images.githubusercontent.com/16630630/41977755-be7b8174-7a52-11e8-8b10-dae4a843a430.png)
![tim 20180627214108](https://user-images.githubusercontent.com/16630630/41977782-d33a6954-7a52-11e8-997f-502a19338f59.png)
我 200% 确定这不是我的问题，因为我翻看源码后发现...语言文件里根本就没有相关的占位符。 
https://github.com/printempw/blessing-skin-server/blob/7ca5d1a39ece832e13c224a0c74e5a96baa7d933/resources/lang/zh_CN/user.yml#L30

**Comment by prinsss** [comment]
对，单纯的只是因为我忘了。感谢反馈。😂

**Comment by prinsss** [comment]
https://github.com/printempw/blessing-skin-server/commit/fdbf74734135b19c41b84d0b084ccdb67f033a34

![Snipaste_2018-07-06_14-52-59.png](https://i.loli.net/2018/07/06/5b3f11d78ae8f.png)

**Comment by tnqzh123** [comment]
还真是简单粗暴…
