### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by ghost** [printempw/blessing-skin-server#12]
1. 后台的确不能通过用户管理删除admin了，但是admin可以在个人资料秒杀自己……
2. 经过部分测试运营，建议在用户管理处增加“修改用户名”选项。
3. **字符串严格语法表达方式**。建议稍加严肃对待与用户交互时显示的文本（特别是提示类信息），如果太过玩笑和乐趣，有可能增加用户的不屑之心里。
4. 缩小左边侧栏，显示的那个BS标题貌似无法通过后台修改，只能修改源文件。

**BUG类：**
黑色主题-白侧边栏主题无法正确显示标题栏，依然是白色。

**Comment by prinsss** [comment]
1. 再怎么说 admin 也不会那么蛋疼吧？删除之前还有密码验证的诶？
2. 已记录
3. 只是稍微卖下萌啦，我会注意的
4. 嗯，因为那个我也不知道用户想要什么，感觉单独加个配置项也不太合适。。本来是打算让用户自己改源码的，既然有需求那我就添加个设置项吧
5. 我这边标题栏是黑色的，并没有问题。具体哪里是白色的呢？

**Comment by prinsss** [comment]
非常感谢你的反馈！有你这样的用户真是太好了呢

**Comment by xfl03** [comment]
3.您自建的皮肤站源码完全由您个人控制，您可以做任何修改(在协议范围内)，也就是说，您完全可以根据您自己的需求将**所有的不符合您的想法的字符串改成您喜欢的认真严肃的内容**。

**Comment by ghost** [comment]
有关于第一条……例如我眼残测试的时候就不小心把自己给删了……我还在奇怪，怎么admin登录不进去了。。。看了一下数据库记录……这尼玛……
那个黑色主题的问题，白侧边栏，我这里标题栏也是白色的。。。
理论上应该是白色侧边栏，黑色顶栏，对吧，我的顶栏（我成了标题栏……）也是白色的……Chrome浏览器。

**Comment by prinsss** [comment]
唔，主题不是我设计的 qwq
估计是作者就是这样设计的吧

我会在 admin 的 profile 页把 delete 的 box 不显示的
