### ISSUE TITLE
[Q] [plugin-api] 请问如何在插件中require第三方composer库？

### ISSUE THREAD

**Issue by cqjjjzr** [printempw/blessing-skin-server#122]
RT，似乎插件并没有提供一个composer.json供使用。我可以自己安装一个吗？

**Comment by prinsss** [comment]
是，直接在插件里新建 `composer.json` 即可，新版的 Blessing Skin 会自动加载插件里的依赖库。参见：https://github.com/bs-community/blessing-skin-plugins/blob/master/textures-qcloud-cos/composer.json

不过新版 BS 还在开发中，v3.4.0 及以下版本的 BS 是不支持自动加载插件的 composer 依赖库的（当然你也可以手动 `require __DIR__.'vendor/autoload.php'`）。

**Comment by tnqzh123** [comment]
这只是我的一个猜测
如果你的站点是使用 Git 上的最新源码构建的，应该也支持自动加载插件 composer 依赖库

**Comment by g-plane** [comment]
文档已更新：https://bs-community.github.io/blessing-skin-plugin-docs/guide/composer.html
