### ISSUE TITLE
由于本站设置，你无法修改昵称

### ISSUE THREAD

**Issue by 8MiYile** [printempw/blessing-skin-server#123]
设置昵称提示:由于本站设置，你无法修改昵称（昵称将被设定为与绑定角色名一致）
请问是插件导致的还是原来就有这个设置？我翻遍了后台都没找到，打开中文角色名也没用

**Comment by prinsss** [comment]
如果你开启了「单角色限制」插件抑或是「数据对接」插件，那么确实是这样的。
