### ISSUE TITLE
不能发送密码找回邮件

### ISSUE THREAD

**Issue by THHakureiReimu** [printempw/blessing-skin-server#124]
Blessing Skin 版本 :3.4.0

试了网易 阿里云 腾讯邮箱 腾讯企业邮箱的SMTP服务器，均在发送邮件时报错：
邮件发送失败，详细信息：Connection could not be established with host hwsmtp.exmail.qq.com [Connection refused #111]

.env文件设置：（腾讯企业邮箱）
MAIL_DRIVER     = smtp
MAIL_HOST       = hwsmtp.exmail.qq.com
MAIL_PORT       = 465
MAIL_USERNAME   = no-reply@xxxxxxxx.com
MAIL_PASSWORD   = xxxxxxxx
MAIL_ENCRYPTION = ssl

怀疑有很大可能是这家虚拟主机的问题。。。打算下一步关闭ssl/tls加密方式试试看，但是不知道怎么关。希望作者大大能提供一些帮助，十分感谢！

**Comment by g-plane** [comment]
试一试将 MAIL_ENCRYPTION 设为 null？

**Comment by prinsss** [comment]
你的虚拟主机封了 SMTP 端口吧？直接去问客服可能比较好。

设置 `MAIL_ENCRYPTION = null` 即可关闭加密。

**Comment by tnqzh123** [comment]
腾讯企业邮箱的 SMTP 服务器是 smtp.exmail.qq.com

**Comment by THHakureiReimu** [comment]
谢谢各位的解答。。。因为是香港主机所以用的 hwsmtp.exmail.qq.com。不过就算是smtp.exmail.qq.com也一样的发不出去。已在主机商处提交售后工单，看看他们能不能解决吧。

**Comment by THHakureiReimu** [comment]
果然是虚拟主机商封锁了邮箱端口，问题已经解决了！

**Comment by prinsss** [comment]
OK
