### ISSUE TITLE
咨询一下关于数据对接的问题，还有一点小建议。

### ISSUE THREAD

**Issue by THHakureiReimu** [printempw/blessing-skin-server#125]
Blessing Skin 版本：3.4.0
运行平台：虚拟主机
PHP 版本：5.6
Web 服务器：Apache
浏览器：Chrome

想在数据对接后统一游戏服务器和皮肤站的密码。现状是在游戏密码修改后，皮肤站的登录密码也会被修改，但是皮肤站的登录密码通过“皮肤站的修改密码”和“皮肤站的找回密码”修改密码后，游戏密码不会被更改。把数据对接配置中的 重复处理 选项改成 用皮肤站数据覆盖目标程序 后，情况则会相反，游戏密码更改后，皮肤站密码不会被更改。
请问如何设置才能实现类似双向同步的功能？我的设想是这样的，皮肤站使用对接目标程序上的用户数据，但是通过“皮肤站的修改密码”和“皮肤站的找回密码”修改密码后，将新密码覆盖到对接目标程序上。
如果现版本不能实现类似功能，可以请在后续版本考虑增加此功能吗？谢谢！

另外还有一点小建议，在需要输入游戏名的输入框旁边有一个邮件图标，可能会造成迷惑。
![qq 20180811003738](https://user-images.githubusercontent.com/11349385/43988186-993f68b6-9d62-11e8-8012-307fd6d4b542.png)

**Comment by prinsss** [comment]
旧版的数据对接插件已不再维护，推荐使用以下插件替代：

Authme 数据对接：
https://github.com/bs-community/blessing-skin-plugins/tree/master/authme-integration
https://coding.net/u/printempw/p/bs-plugins-archive/git/blob/master/authme-integration_v1.0.1.zip

CrazyLogin 数据对接：
https://github.com/bs-community/blessing-skin-plugins/tree/master/crazylogin-integration
https://coding.net/u/printempw/p/bs-plugins-archive/git/blob/master/crazylogin-integration_v1.0.1.zip

论坛数据对接：
https://github.com/bs-community/blessing-skin-plugins/tree/master/forum-integration
https://coding.net/u/printempw/p/bs-plugins-archive/git/blob/master/forum-integration_v1.0.1.zip

**Comment by prinsss** [comment]
新版的 Authme、CrazyLogin 等数据对接插件可以直接使用 BS 的 `users` 表作为登录插件的数据表，应该可以完美解决上述「密码未同步」的问题。详见：https://github.com/bs-community/blessing-skin-plugins/tree/master/authme-integration#%E9%85%8D%E7%BD%AE-authme

**Comment by THHakureiReimu** [comment]
emmmm 绑定角色名后管理员账号变成普通账号了。。。 请问怎样给自己账号提权呢？

**Comment by prinsss** [comment]
之前好像也有人遇到这个问题了，你在用什么插件？能复述一下你的操作过程吗？

设置超级管理员：https://github.com/printempw/blessing-skin-server/wiki/%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85-Blessing-Skin#-%E6%96%B0%E5%BB%BA%E7%AE%A1%E7%90%86%E5%91%98%E8%B4%A6%E6%88%B7

**Comment by THHakureiReimu** [comment]
对接的是Authme登录插件。
皮肤站使用的插件：单角色限制、Authme 数据对接、BS 缓存、材质举报 。均为最新版本。

因为使用的是香港虚拟主机，所以网站架在虚拟主机上，数据库架在游戏服务器上。重新设置.env为国内游戏服务器的地址，统一加密方式为SHA256。然后再新建blessing-skin数据库，之后安装blessing-skin server，修改Authme配置，指定数据库为blessing-skin并设置配置参数，再启动游戏服务端。再进入blessing skin 插件配置中启用所有插件，先启用单角色限制 后启用Authme 数据对接后弹出需要绑定角色名的窗口，绑定后刷新页面，超级管理员权限变成普通用户权限。

**Comment by THHakureiReimu** [comment]
另外对接后，不能从游戏里注册账号了。Authme报错 [AuthMe] Error during SQL operation: [SQLException]: Field 'score' doesn't have a default value

**Comment by prinsss** [comment]
什么版本的 Authme？

**Comment by THHakureiReimu** [comment]
Authme版本：5.3.2
MySQL版本：Windows x64 5.7.22

**Comment by prinsss** [comment]
我用 Authme 5.4.0 测试时倒是没问题的……

临时解决方法，在你的皮肤站数据库中运行以下 SQL 语句（如果有表前缀的话记得加上）：

```sql
ALTER TABLE `users` MODIFY `email` varchar(100) NULL;
ALTER TABLE `users` MODIFY `score` int(11) NULL;
ALTER TABLE `users` MODIFY `ip` varchar(32) NULL;
ALTER TABLE `users` MODIFY `last_sign_at` datetime NULL;
ALTER TABLE `users` MODIFY `register_at` datetime NULL;
```

**Comment by THHakureiReimu** [comment]
好的 运行完就可以注册了

**Comment by THHakureiReimu** [comment]
还有一个问题：使用Authme注册账号后，默认的邮箱地址会填成'your@email.com' ，登录皮肤站后也不会提示修改默认邮箱。。

**Comment by prinsss** [comment]
……不考虑升级至 Authme 5.4.0 吗？

https://github.com/AuthMe/AuthMeReloaded/blob/5.3.2/src/main/java/fr/xephi/authme/data/auth/PlayerAuth.java#L247

https://github.com/AuthMe/AuthMeReloaded/blob/5.4.0/src/main/java/fr/xephi/authme/data/auth/PlayerAuth.java#L222

**Comment by THHakureiReimu** [comment]
我这就去升级！ 添麻烦了 不好意思
