### ISSUE TITLE
为什么角色名最少要求3个字？

### ISSUE THREAD

**Issue by suoyukii** [printempw/blessing-skin-server#126]
为什么角色名最少要求3个字？
很多人的名字都两个，例如：籽岷、炎黄

**Comment by g-plane** [comment]
演示站的问题不要在这里发

**Comment by prinsss** [comment]
因为 Mojang 官方要求角色名长度不少于 3，而且据反馈有些服务端插件无法正确处理角色名长度小于 3 时的情况。如果有需要，请自建皮肤站，后台中有角色名长度限制的配置项。

**Comment by tnqzh123** [comment]
其实现在要求放宽了，貌似不少于 2 就行

**Comment by prinsss** [comment]
演示站现在的现在的角色名规则是：允许字母、数字、下划线以及 CJK 字符，长度要求 1-16。（之前升级后忘记修改了）
