### ISSUE TITLE
批量导入 消除中文乱码后异常

### ISSUE THREAD

**Issue by ShallowAi** [printempw/blessing-skin-server#127]
## The Problem 问题描述

批量导入 消除中文乱码后异常，不消除即乱码

## Environment 运行环境

- Blessing Skin 版本 / 3.5.0
- 虚拟主机还是 VPS / virtual hosting
- PHP 版本 / 7.0.31
- Web 服务器 / IIS
- 错误链接 / admin/batch-import?step=3&type=steve&uploader=1

## Error Message 错误信息

https://s1.ax1x.com/2018/09/01/Px3726.jpg
https://s1.ax1x.com/2018/09/01/Px3xIA.jpg

## Steps to Reproduce 重现步骤

批量导入，填写目录（英文），勾选尝试消除乱码，下一步，开始导入，异常

https://s1.ax1x.com/2018/09/01/Px8SPI.jpg

**Comment by prinsss** [comment]
你使用的是什么版本的「批量导入」插件？最新版是 2.0.0。

**Comment by ShallowAi** [comment]
@printempw 最新版本 2.0.0

**Comment by prinsss** [comment]
你是在「预览页面」出现的乱码还是在开始导入时出现的乱码？请截图截整个页面。
不勾选「尝试消除乱码」呢？

**Comment by ShallowAi** [comment]
不勾选 直接看不见
![20180901233516](https://user-images.githubusercontent.com/21982139/44947443-b3f2b300-ae3f-11e8-8714-1357f5966642.jpg)

**Comment by prinsss** [comment]
勾选「尝试消除乱码」后，是在点击「开始导入」后跳转至的新页面上报错的吗？请提供一下完整的页面截图。

**Comment by ShallowAi** [comment]
![20180901233942](https://user-images.githubusercontent.com/21982139/44947496-5317aa80-ae40-11e8-991a-041ede712a3b.jpg)

**Comment by prinsss** [comment]
好的，情况我了解了，将尝试修复，有结果的话再回复你。

**Comment by prinsss** [comment]
下载 [`BatchImportController.php`](https://gist.github.com/printempw/b5263420d103125626fbe4ec58464560/raw/c156a2416cddd3da7977e80acf1ee034b8a29e1c/BatchImportController.php)，将其放入 `plugins/batch-import/src` 目录并覆盖原文件，再尝试进行批量导入。如果再次遇到报错，请提供截图与 `/storage/logs` 下的日志文件。

**Comment by prinsss** [comment]
通过上述方法问题是否已经解决？
