### ISSUE TITLE
开启论坛数据对接后提示严重错误，几乎所有功能无法使用

### ISSUE THREAD

**Issue by keven1229** [printempw/blessing-skin-server#131]
## The Problem 问题描述

在开启论坛数据对接后显示严重错误然后无法访问一切与用户相关的页面(如用户中心/管理面板等)

## Environment 运行环境

- Blessing Skin 版本 
3.5 从release下载
- 虚拟主机还是 VPS
阿里云轻量应用服务器(应该算vps吧)
- PHP 版本 / version of PHP
7.2
- 什么 Web 服务器，Apache 还是 Nginx
Nginx 1.14
- 什么浏览器，出现错误时的地址栏 URL 是什么
Firefox(Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0)
skin.*****.com:88/admin/plugins/market

## Error Message 错误信息

SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: select * from `` where `email` = keven@*****.com limit 1)

## Steps to Reproduce 重现步骤

在插件市场安装论坛数据对接插件然后点击启用
之前安装单用户限制后未启用然后又安装了论坛对接，先点击了论坛数据对接的启用然后提示要绑定角色(好像叫这个)，在绑定完角色名后启用论坛数据对接后出现此错误

## Attachments 附件

没有找到storage/logs/laravel.log文件
开启APP_DEBUG后的截图:
![2018-12-18 17-55-36](https://user-images.githubusercontent.com/41236776/50146312-703c9000-02ee-11e9-9c5e-d5fee5e742e7.png)

**Comment by prinsss** [comment]
你没有配置好目标数据库的用户数据表名。

请尝试删除数据库 `options` 表中 `option_name` 为 `forum_db_config` 的字段，并在 `plugins` 目录下删除 `forum-integration` 插件，然后再次尝试安装「论坛数据对接」插件。

如果问题依旧，届时请提供 `/storage/logs` 目录下的 `.log` 日志文件。

**Comment by keven1229** [comment]
已尝试你所提供的方法但是没有用。
在删除`forum_db_config`并删除插件文件后重新安装依然是原先的提示
按照插件市场中的[使用说明](http://t.cn/RDEq0aH)所说，配置好密码加密算法后下一步为修改插件配置文件，但是修改配置文件要先启用插件(还是说我没有找到有别的方式在启用之前修改配置文件？)，而启用插件后就出现了一开始的那个错误
log:
[bs-7fd2cf82f5146ca6.log](https://github.com/printempw/blessing-skin-server/files/2690864/bs-7fd2cf82f5146ca6.log)

**Comment by hempflower** [comment]
同样有这个问题，启用时会提示:SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name " (SQL: select * from " where 'email' = 1993996310@qq.com limit 1)

**Comment by prinsss** [comment]
@hempflower 临时解决方法，将数据库 `options` 表中 `forum_db_config` 的值手动修改为 ：

```text
a:6:{s:4:"host";s:9:"127.0.0.1";s:4:"port";s:4:"3306";s:8:"database";s:0:"";s:8:"username";s:8:"username";s:8:"password";s:6:"secret";s:5:"table";s:0:"";}
```

**Comment by hempflower** [comment]
> @hempflower 临时解决方法，将数据库 `options` 表中 `forum_db_config` 的值手动修改为 ：
> 
> ```
> a:6:{s:4:"host";s:9:"127.0.0.1";s:4:"port";s:4:"3306";s:8:"database";s:0:"";s:8:"username";s:8:"username";s:8:"password";s:6:"secret";s:5:"table";s:0:"";}
> ```

OK！现在正常了，谢谢:)
