### ISSUE TITLE
第三方更新源

### ISSUE THREAD

**Issue by hempflower** [printempw/blessing-skin-server#132]
http://bs-mirror.i-creator.cn/update.json
CDN:http://bs-mirror.i-creator.cn/resources

**Comment by g-plane** [comment]
![default](https://user-images.githubusercontent.com/17216317/50573747-a280de00-0e14-11e9-9b35-51d638bcb76e.png)

**Comment by hempflower** [comment]
![qq 20190101223240](https://user-images.githubusercontent.com/22955496/50573772-25a23400-0e15-11e9-801b-9eccba93291d.png)
![qq 20190101223149](https://user-images.githubusercontent.com/22955496/50573781-44a0c600-0e15-11e9-8179-5ec33634a0df.png)

**Comment by g-plane** [comment]
如何称呼这个站点？

**Comment by hempflower** [comment]
MaHua's mirror吧

**Comment by g-plane** [comment]
已添加，thx

**Comment by yushijinhun** [comment]
不支持https？

**Comment by hempflower** [comment]
@yushijinhun 时间匆忙，所以没弄，如果有需求的话明天中午弄上。
