### ISSUE TITLE
v4 在执行安装向导前仍需在 .env 中手动填写数据库信息

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#133]
在 v4 分支的最新提交中，尽管已经支持了数据库配置向导，但是仍然需要在 `.env` 文件中手动填写**正确的**数据库信息才可以执行安装程序。
如果没有在 `.env` 文件中填写好数据库信息，访问 `/setup` 仍然会报错：
```
SQLSTATE[HY000] [1049] Unknown database 'fuck' (SQL: select * from information_schema.tables where table_schema = fuck and table_name = bs_users)
```

**Comment by g-plane** [comment]
目前确实是这样的，因为执行安装向导的时候仍进行了数据库检查，~~我考虑过要不要在分发的时候指向一个临时的 SQLite 文件。~~
