### ISSUE TITLE
能否让皮肤库功能需要管理员权限才能访问

### ISSUE THREAD

**Issue by ShallowAi** [printempw/blessing-skin-server#134]
## The Problem 问题描述

能否让皮肤库功能需要管理员权限才能访问

## Environment 运行环境

- Blessing Skin 版本 3.5.0

**Comment by g-plane** [comment]
这种需求不多见啊，不过你可以通过编写插件来实现。

**Comment by g-plane** [comment]
你可以像这样编写插件，下面是 `bootstrap.php` 的源码（随手写的，不保证正确性）：

```php
return function () {
    $user = app('users')->get(session('uid'));

    if (request()->is('skinlib/*') && ! $user->isAdmin()) {
        return abort(403, trans('auth.check.admin'));
    }
};
```

具体如何制作一个插件，可移步 [插件开发文档](https://bs-community.github.io/blessing-skin-plugin-docs/)。

**Comment by g-plane** [comment]
不考虑实现这个特性（除非真的有较大的呼声）。我关闭 issue 了，如果有问题可以继续讨论。
