### ISSUE TITLE
可否考虑增加 NSFW filter？

### ISSUE THREAD

**Issue by dz-paji** [printempw/blessing-skin-server#135]
有些用户可能会上传一些 NSFW 材质，但不将其设置为私有材质。为了减轻审查的负担，也为了避免直接删除而使用户不满的情况出现，能否增加一个 NSFW filer(类似 pixiv)? 在文件上传时询问用户是否将材质设置为 NSFW。这样，在用户访问皮肤库时，filer 默认开启，过滤掉被打上了 NSFW 的材质. 若用户想要看到这些材质，则需手动关闭 filer.

**Comment by g-plane** [comment]
「不将其设置为私有材质」会是因为没看到选项还是故意不使用这个选项（例如积分不够）？

**Comment by dz-paji** [comment]
我看到的大部分是因为积分不够而没有去使用私有材质的。在材质的上传页面，有一个高亮的文本框用以提示，若材质具有争议性，则需设置为私有材质.

**Comment by tnqzh123** [comment]
感觉这个 NSFW 标签和开源协议一样，只防君子不防小人...
我在 LittleSkin 的私密材质的积分说明里加入了「积分不够用？你可以使用 TinyPNG 对图片进行压缩后上传」的提示，但是很多人还是会把未经压缩的文件上传到皮肤库中并不设为私密。
更麻烦的是很多材质都在打擦边球，不好处理...

**Comment by g-plane** [comment]
我发现了一个工具：https://github.com/alexkimxyz/nsfw_data_scrapper
