### ISSUE TITLE
拖动改变浏览器窗口大小会导致人物预览越来越大……

### ISSUE THREAD

**Issue by KichikuNya** [printempw/blessing-skin-server#136]
RT
拖动改变浏览器窗口大小会导致用户中心右侧的人物皮肤预览越来越大

**Comment by g-plane** [comment]
可以给出更多信息吗？

**Comment by tnqzh123** [comment]
大概应该是说，在拖动浏览器窗口的边框对浏览器窗口进行放大操作的时候，材质预览的那个 div 会跟着放大；但是当缩小浏览器窗口的时候，材质预览的那个 div 还会是那么大，不会缩回去。

**Comment by KichikuNya** [comment]
> 
> 
> 可以给出更多信息吗？

没有更多信息了，试试看就知道了，PC端浏览器应该都可以

**Comment by KichikuNya** [comment]
> 
> 
> 可以给出更多信息吗？

就是拖动浏览器边框来改变窗口大小不管拉大还是拉小预览的人物模型都会越来越大

**Comment by xfl03** [comment]
直接关了？

**Comment by tnqzh123** [comment]
@xfl03 这种提出 Issue 的人都不配合的 Issue 还有什么开着的必要吗(
