### ISSUE TITLE
BS3.5升级至4.0出错

### ISSUE THREAD

**Issue by 8MiYile** [printempw/blessing-skin-server#137]
## 运行环境
- Blessing Skin 版本 / 4.0
- 虚拟主机 / cPanel 2.6.32-673.26.1.lve1.4.18.el6.x86_64
- PHP 版本 / 7.2
- Apache 版本 / 2.4.37
- Google Chrome 版本 / 73.0.3683.4，
- 访问出错的链接 https://mas.8yl.tech/

## 错误信息
Fatal error: Call to undefined function runtime_check() in /home/p2487/public_html/authskin/index.php on line 24

## 重现步骤
原来的Blessing Skin 版本是3.5.0 然后覆盖4.0的文件导致出现此问题

## 问题描述
你好作者，我的服务器是虚拟主机，采用的是cPanel虚拟面板管理程序，PHP版本是7.2，Apache版本是2.4.37，使用的浏览器是Google Chrome<日更版>，最后的操作是使用了v4的源码覆盖了v3.5.0导致的出错，谢谢你能看到我的问题

## 附件
没有附件

**Comment by tnqzh123** [comment]
v4 还没有正式发布吧
仓库的 v4 分支里的是不含依赖也未经编译的源码，不能直接使用的
虚拟主机没办法通过 Composer 安装依赖，也没办法通过 Yarn 编译前端代码，至少是现阶段应该没办法用 v4，老老实实用着 v3.5.0 吧，别那么着急

**Comment by g-plane** [comment]
感谢反馈，不过最近有点忙，需要稍迟一段时间才能去了解这个问题，可能不能及时答复，请见谅。

另外也感谢测试 v4，如果在试用 v4 的过程中发现有问题，也欢迎指出。

~~我这么说会不会被打？~~

**Comment by g-plane** [comment]
v4 中不存在 `runtime_check` 函数，所以，你可以试着在保留数据库和 `storage` 目录的情况下，删除其它文件及目录，然后执行安装。
