### ISSUE TITLE
可否批量上传皮肤？

### ISSUE THREAD

**Issue by year9** [printempw/blessing-skin-server#138]
The Problem 问题描述

无法批量上传皮肤

**Comment by dz-paji** [comment]
可在後_批量肫つw

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by year9** [comment]
您好，在哪个选项呢




------------------ 原始邮件 ------------------
发件人: "dz_paji"<notifications@github.com>;
发送时间: 2019年2月4日(星期一) 下午4:08
收件人: "printempw/blessing-skin-server"<blessing-skin-server@noreply.github.com>;
抄送: "锦华网络工作室"<12197673@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [printempw/blessing-skin-server] 可否批量上传皮肤？ (#138)



可在後_批量Œ肫つw 
 
 Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10 
 
 ________________________________

**Comment by tnqzh123** [comment]
请在插件市场自行搜索相关插件。

**Comment by g-plane** [comment]
@tnqzh123 已经给出了解决办法。
