### ISSUE TITLE
插件市场中搜索框不可用

### ISSUE THREAD

**Issue by yushijinhun** [printempw/blessing-skin-server#139]
## The Problem 问题描述
在插件市场的右上角搜索框中输入任意文字，得到以下报错：
![default](https://user-images.githubusercontent.com/8373027/52789510-f7b04080-309e-11e9-8c24-02c1ba26e2e6.png)

## Environment 运行环境
- Blessing Skin 版本 / version of Blessing Skin: v3.5.0

**Comment by g-plane** [comment]
可以试试 v4 的吗？如果 v4 没有就直接关闭这个 issue 了，因为 v3 不再更新。（也许）

**Comment by g-plane** [comment]
v3 不再更新。
