### ISSUE TITLE
index.php 有一处XSS

### ISSUE THREAD

**Issue by hcrgm** [printempw/blessing-skin-server#14]
俺根据源代码，构造了这个地址：http(s)://**/index.php?msg=6666%22);%3C/script%3E%3Cscript%3Ealert(%22hack!!

你打开会显示“hack!!”的
，可以做很多事哦
修复方案：htmlspecialchars，你懂得~
同是玩web的，不应该哈
我还没开始找其它注入点，建议全部排查

**Comment by ZhaiSoul** [comment]
所以说前端最容易出这种问题的（摊手
不过XSS漏洞的话，目前绝大部分杀软应该都可以拦截了的吧

**Comment by prinsss** [comment]
哎呀哎呀真是大意了，感谢指出！
其他照理来说是没有注入点的，不过也有可能我还要哪里疏忽了 qwq
我把 msg 的实现方式改成 session 好了。
