### ISSUE TITLE
无法进行安装

### ISSUE THREAD

**Issue by WindyCloudCute** [printempw/blessing-skin-server#140]
无法进行安装

## Environment 运行环境

- Blessing Skin 版本 3.5.0
- 服务器是VPS
- PHP 7.1
- 服务器用的是nginx
- 用的是谷歌浏览器[Edge并不会出现这个问题] 出错页面是http://./setup

## Error Message 错误信息
[这是截图](https://fengzi.run/0.png)

出现错误
unserialize(): Error at offset 0 of 40 bytes
如果你是访客，这说明网站程序出现了一些错误，请稍后再试或者联系站长。
如果你是站长，那么请开启 .env 中的 APP_DEBUG 查看详细信息。

**Comment by g-plane** [comment]
请开启 .env 中的 APP_DEBUG 查看详细信息，然后把信息发上来。（如有敏感信息可以打码）

**Comment by WindyCloudCute** [comment]
好吧好像没问题了 =.=
