### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by MeTerminator** [printempw/blessing-skin-server#144]
## The Problem 问题描述

在phpsturdy中，无论怎么调试，始终显示403 Forbidden，

## Environment 运行环境
- VPS
- 7.0.12
- Apache
- http://192.168.50.181/index.php/setup
-360极速浏览器

## Error Message 错误信息

没有错误信息，程序未被加载
ps：这个报错应该是.htaccess的问题，但我又不知道怎么改。。。

## Steps to Reproduce 重现步骤

只要目录下有.htaccess文件，则会报错
我的配置为
`<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # You may need to uncomment the following line for some hosting environments,
    # if you have installed to a subdirectory, enter the name here also.
    #
    # RewriteBase /

    # Black list protected files
    RewriteRule (^\.|/\.) - [F]
    RewriteRule ^storage/.* - [F]

    # Redirect trailing slashes if not a folder
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle front controller
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
`

**Comment by g-plane** [comment]
如果要进行安装，应该访问 `/setup`，而不是 `/index.php/setup`。
