### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by 0xd1cf001e** [printempw/blessing-skin-server#145]
## The Problem 问题描述

404 Not Found

## Environment 运行环境

请填写以下内容 / Please tell us about your environment.

- Blessing Skin 版本 / 3.5
- 虚拟主机还是 VPS / 本地电脑
- PHP 版本 / version of 7.3.3
- 什么 Web 服务器，Apache 还是 Nginx / apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 / Google Chrome 所有页面

## Steps to Reproduce 重现步骤
按照安装向导安装，最后一步输入localhost，自动跳转至localhost/setup，显示404，访问local host/index.php/setup除了css没有加载其它一切正常

**Comment by g-plane** [comment]
伪静态有没有配置好？

**Comment by 0xd1cf001e** [comment]
我也不知道，伪静态用的就是安装包里的.htaccess文件

**Comment by g-plane** [comment]
可参考：https://github.com/printempw/blessing-skin-server/wiki/FAQ#404-not-found

**Comment by 0xd1cf001e** [comment]
服务器配置没问题，除了主页，其它的都要加一个/index.php才能正常访问，localhost 正常,localhost/auth/login 404 localhost/index.php/auth/login 访问正常，但没有加载css

**Comment by g-plane** [comment]
Apache 中的伪静态模块有没有开启？

**Comment by g-plane** [comment]
如果实在不行，可以考虑使用 Nginx，并按照 wiki 中的指南进行配置 Nginx。

**Comment by 0xd1cf001e** [comment]
额。。。确实是伪静态模块没开。。。白折腾了几个小时，nginx也白装了。。。。。。😭😭😭

**Comment by g-plane** [comment]
那问题解决了吗？

**Comment by 0xd1cf001e** [comment]
正在试

**Comment by g-plane** [comment]
顺便一提，本仓库不再更新。后续的更新会在 https://github.com/bs-community/blessing-skin-server 发布。

**Comment by 0xd1cf001e** [comment]
问题已解决
