### ISSUE TITLE
postgresql报错

### ISSUE THREAD

**Issue by gundami** [printempw/blessing-skin-server#146]
数据库改为postgresql后在管理员账户的”管理面板“处报错

- 3.5
- VPS
- PHP 7.2
- Apache
- chrome，http://118.25.90.139/admin

错误信息：

SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: timestamp without time zone ~~ unknown LINE 1: ...unt(*) as aggregate from "users" where "register_at" LIKE $1 ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: select count(*) as aggregate from "users" where "register_at" LIKE %2019-03-25%)

登录管理员用户，选择管理面板，之后就报错

**Comment by g-plane** [comment]
4.0.0 将于近期发布，因此 3.x 将不再接收任何功能请求或 bug 报告。

新项目地址：https://github.com/bs-community/blessing-skin-server

感谢您的使用。
