### ISSUE TITLE
Phpwind 支持？

### ISSUE THREAD

**Issue by alejandroxin93** [printempw/blessing-skin-server#15]
可不可以考虑加入对phpwind的支持呢？

**Comment by prinsss** [comment]
嗯，那你可以提供下 phpwind 的用户数据表的结构以及密码的加密算法吗？

**Comment by alejandroxin93** [comment]
好的，请待我帮你总结哈。

**Comment by alejandroxin93** [comment]
还有一个问题，登陆之后会在页面左上角显示一个玩家头像，头像地址为："../blessing-skin/avatar/%NUMBER%/%USERNAME%.png" 然后在根目录里面并没有这个文件夹avatar，手动创建png文件及文件夹之后，在浏览器里面怎么都打不开这个png，页面也不显示。
我可以确定安装正确，注册登录等功能一切正常，除了打不开这个图片。

**Comment by alejandroxin93** [comment]
phpwind 密码加密算法：
`<?php
$realpassword = "123456";
$salt = "xxxxxx";
$password = md5(md5($password).$salt);
?>`
数据库：
数据库名字：自定    eg：phpwind_forum （我看到配置里面没有数据库名字的设置，并且论坛所使用的数据库和DB_skin数据库不在一起，所以希望可以增加自定义对接数据库名字）

数据表：
表名字：“PREFIX_windid_user”    (建议直接自己填写)

字段：
用户id：“uid”    eg：2、9、10
用户名：“username”    eg：alejandro、abcdef
加密后的密码：“password”    eg：86293aa6537d717630bb4031e43a3058
椒盐参数：“salt”    eg：tL695C
用户注册ip：“regip”    eg：1.2.3.4

**Comment by alejandroxin93** [comment]
请忽略掉增加自定义对接数据库名字设置的请求。直接把DB_SKIN设置为论坛数据库就可以了。是我傻了。。。

**Comment by prinsss** [comment]
/avatar/{size}/{username}.png 这个是根据用户皮肤自动生成的头像，没有 avatar 文件夹是正常的

**Comment by prinsss** [comment]
已更新 v2.4.5，加入了对 Phpwind 的支持，试试看吧？

**Comment by alejandroxin93** [comment]
好迅速，我来看看！
