### ISSUE TITLE
站点配置提交出错

### ISSUE THREAD

**Issue by alejandroxin93** [printempw/blessing-skin-server#16]
例如，在设置站点公告之后，点击提交，会出现Function ereg() is deprecated错误，原因是ereg()早已在php 5.3的时候废掉了，而现在大多数都在使用5.5左右的版本。
解决办法，找到../admin/options.php的第40行，将
`($key == "site_url" && ereg("/$", $value))`
修改为
`($key == "site_url" && preg_match("/.*(\/)$/", $value))`。
就可以正常判断url末尾是不是有斜杠了。

**Comment by prinsss** [comment]
哦哦！感谢反馈！
已经记录，将在下一个版本修复
