### ISSUE TITLE
用5.4/5.6尝试跑改程序 都非常卡

### ISSUE THREAD

**Issue by Zerek-Cheng** [printempw/blessing-skin-server#17]
用5.4/5.6尝试跑改程序 都非常卡

**Comment by xfl03** [comment]
请问卡是指网页生成速度慢还是CPU/内存占用大？

**Comment by Zerek-Cheng** [comment]
http://zero.50zf.com:82/

你可以试试
http://zero.50zf.com:82/a.php

这是phpinfo页面

**Comment by Zerek-Cheng** [comment]
请问是否有解决方案？

**Comment by prinsss** [comment]
呃，你确定你给出的 URL 现在部署的是 Blessing Skin Server？
![screenshot](https://ooo.0o0.ooo/2016/06/30/5775f2d03a278.png)

**Comment by Zerek-Cheng** [comment]
= =我刚刚在测试用你的旧版

在 2016-07-01 12:31:17，"printempw" notifications@github.com 写道：

呃，你确定你给出的 URL 现在部署的是 Blessing Skin Server？

**Comment by Zerek-Cheng** [comment]
用旧版程序（2.4.3）

卡的情况有所缓解

**Comment by prinsss** [comment]
你倒是给个部署了 Blessing Skin Server 并出现卡顿的地址啊，不然我也没法知道是什么原因啊
现在你给出的 http://zero.50zf.com:82/ 部署的是其他程序

**Comment by Zerek-Cheng** [comment]
是的我也不知道为什么 所以换了一套

**Comment by prinsss** [comment]
那你能部署下 Blessing Skin Server 吗，不看一下的话我也不知道是什么问题
