### ISSUE TITLE
皮肤站使用CDN后部分功能异常

### ISSUE THREAD

**Issue by g-plane** [printempw/blessing-skin-server#18]
由于我将皮肤站架设在国外主机，为了提高访问速度，我使用了CloudFlare的CDN。但使用CDN后皮肤预览功能失效，同时上传皮肤的界面也变成普通的“浏览文件”文字按钮。望作者能在下一版本中增加对CDN的支持。

**Comment by prinsss** [comment]
这是因为资源文件没加载完全吧
你开一下 F12，看看控制台有什么报错

**Comment by g-plane** [comment]
preview.utils.js:1 Uncaught TypeError: Cannot read property 'get3dSkinCanvas' of undefined

**Comment by prinsss** [comment]
[assets/libs/skin-preview/three.msp.js](https://github.com/printempw/blessing-skin-server/blob/v2/assets/libs/skin-preview/three.msp.js) 这个文件没加载吧

**Comment by g-plane** [comment]
那应该怎么处理？

**Comment by prinsss** [comment]
你把你站点的地址给我吧，我看看是哪里出了问题

**Comment by g-plane** [comment]
www.mcskin.cf    需要管理员账号吗？

**Comment by prinsss** [comment]
我看了一下，你用的 CDN 是这样加载脚本的：
![](https://ooo.0o0.ooo/2016/07/21/57918c7bd686d.png)
估计是因为这个导致加载顺序出错了

**Comment by prinsss** [comment]
V3 我把库文件都压缩到一个文件里了，应该会对 CDN 更友好些，过几天就可以发布

**Comment by g-plane** [comment]
谢谢，麻烦您了。
