### ISSUE TITLE
V3-beta出现HTTP 500错误

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#19]
如题hhhh
<img src="http://lpb.littleservice.cn/images/2016/07/26/QQ20160726115037ff380.png" alt="QQ20160726115037ff380.png" border="0" />
本来是v2.4.5 今天删了原来的所有文件然后就这样了
地址<a href="http://mcskin.littleservice.cn/index.php">http://mcskin.littleservice.cn/index.php</a>（注意末尾的index.php）

**Comment by prinsss** [comment]
你把 .env 里的 DEBUG 改成 true 应该就会有详细信息了

**Comment by tnqzh123** [comment]
我能表示看不懂么Orz
不太方便截图麻烦自己访问一下那个链接OwQ

**Comment by prinsss** [comment]
好吧，我 GitHub readme 上应该更新了的，v3 需要 PHP >= 5.5.9

**Comment by tnqzh123** [comment]
readme并没有更新Orz

**Comment by prinsss** [comment]
https://github.com/printempw/blessing-skin-server#环境要求
