### ISSUE TITLE
一些发展建议

### ISSUE THREAD

**Issue by ghost** [printempw/blessing-skin-server#2]
只是一些个人的建议，我会慢慢补充的。

**关于仪表盘（针对管理员）：**
1. 加入允许注册和禁止注册选项（这真的很重要，特别是对于那些只是用于自己服务器的朋友们...）；
2. 禁止管理员admin被删除（这很重要。。。谨防手残）。
3. 加入后台添加用户的功能（这也很重要，参见第一条）。

**关于新用户注册：**
1. 加入邮件验证机制；
2. 验证码（可有可无）。

**其他一些问题：**
1. 有关仪表盘用户的“#”编号我还没看懂，为啥管理员是1，再注册一个就是……15了……
我的建议：去除用户编号，以用户名的字符串解决一切问题而不是编号，避免强迫症。
所谓用户编号这个被称为UID的东西已经在phpwind和Discuz中留下了很多问题，甚至MC的物品ID也造成了很多很多的问题，因此能避开这种数字自排序ID，就尽量不用。
2. 加入UUID识别功能。
对于皮肤站那肯定首打离线模式了（……在线模式……嗨说白了真正的正版用户还用得着皮肤站……），那么首先，离线模式的UUID是服务端根据用户名自动生成的，这个算法也很简单，您可以让皮肤站也按照UUID来办事（离线模式嘛，根据用户名获取UUID），意思就是，不用我上面说的那个编号而是UUID，这岂不是一举两得呢。

其他问题有待补充完善。

**Comment by prinsss** [comment]
1. 已在日程中，不过我要要到周末才能更新
2. 记下了
3. 已在日程中，同时还有批量添加功能（用于自定义 NPC 的皮肤）
4. 邮件认证啊，感觉没多大必要，有 ip 限制也不用怕恶意注册，而且又是个人皮肤站
5. 待商榷
6. 自增 ID 还是需要的，用于主键和索引。用 id 来查找比用 username 查找快很多，尤其是以后需要加入其它一对多数据关系的时候。强迫症的话，我把那一列去掉好了（笑
7. 同上，UUID 太长了，没大必要

**Comment by ghost** [comment]
啊咧，去掉那一列！（强迫症在此灭杀自我……）

`* （@论我不是盗版但是我想要披风……#@%#$!@!@#!@%!@^……）`

**Comment by xfl03** [comment]
uuid是基于java uuid算法随机生成的，并不能通过uuid获得唯一的用户名/用户名唯一uuid。
正版是将第一次生成的uuid保存在数据库中实现的。

**Comment by prinsss** [comment]
关闭注册、禁止删除 admin、批量添加用户已实现，请查看最新的 release。
至于管理页的 uid，我觉得蛮好看的就没删（笑）如果你强迫症发作的话，我告诉你怎么删掉好了
