### ISSUE TITLE
“我的衣柜”中皮肤右下角“更多”按钮易被AdBlock屏蔽

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#20]
之前这个问题在MCBBS反映过的。。。
当时说的是并没有发现“更多”按钮
后来经查是AdBlock的锅Orz
用的AdBlock Plus

**Comment by prinsss** [comment]
WTF，我也用的 ABP 啊
你是不是以前屏蔽过哪个网站的标签为 .more 的元素啊

**Comment by tnqzh123** [comment]
装完ABP就放那里没管它了
只添加过几个网站到白名单

**Comment by prinsss** [comment]
我换了个浏览器也用 ABP，测试了本地环境和线上环境，试了好久也没有复现出这个问题来 (;´Д`)
