### ISSUE TITLE
对Blessing Skin Server v3的几点建议

### ISSUE THREAD

**Issue by g-plane** [printempw/blessing-skin-server#21]
1. 个性化设置的配色，可以通过数值自定义RGB颜色。
2. v2到v3，旧用户的名字作为`nickname`，然后允许用户以`nickname`登录（新老用户都能以`nickname`登录）。接着提示或强制用户补充邮箱信息。如果是提示，则让用户补充邮箱信息后奖励积分。如果是强制，则在用户补充邮箱信息后才允许进行其它操作。
3. 每个目录下创建空的`index.html`防止列出目录内容。
4. 注册之后还需要登录。为什么不能注册之后直接跳转进去用户中心？
5. 从皮肤库添加皮肤到自己的衣柜时，要求填写皮肤名字，默认是空的。能不能改为默认是原来皮肤已有的名字，让懒人~~（例如我）~~直接快速添加？
6. 在皮肤库中点击皮肤的哈希值可以下载皮肤，但建议文件名应为`皮肤名称.png`。
7. 能不能加个自定义积分换算，例如默认是1 score = 1KB，然后我可以设置成5 score = 1KB。另外是否考虑加个签到随机数范围设置。（默认是10~100吧？）
8. 用户管理页面考虑一下添加“设为管理员”和“取消管理员”按钮
9. 签到时间计算能否可以可选择地设置像Discuz的dsu签到插件以每天的0时计算签到周期？  
   10.站点公告支持`Markdown`就好了

**Comment by prinsss** [comment]
1. 主题的话，真想要自定义的都自己去改 CSS 样式了，而且整个站点又不是只有一种主色，提供 RGB 的颜色配置是不现实的
2. 不错的方法，我会考虑加入
3. 自己去把 nginx/apache 的 autoindex 关掉
4. 采纳
5. 采纳~~（其实我本来打算这样的，后来因为懒就算了）~~
6. 这个挺麻烦的，因为存储的文件就是没有后缀的。不过可以用些奇怪的方法，纳入考虑
7. 采纳
8. 这个本来是有想的，但后来考虑了一下，不知道怎么样算做超级管理员好（就是可以设置/取消其他管理员），目前是考虑 uid = 1 或者 permission = 2，你有什么想法吗？
9. 考虑添加选项
10. 不想再增加 Markdown 解析库啦，你写了 MD 以后转换成 HTML 填进去吧

非常感谢你的建议~ (*´ω`*)

**Comment by g-plane** [comment]
对于第6点，我记得Discuz中的附件功能就是类似的，它在文件储存中的命名规则是`Base64编码.原有的后缀`，然后下载的时候可以得到它真正原来的文件名。
对于第8点，我喜欢permission = 2，因为mc服务器里server.properties就是这样的。

**Comment by prinsss** [comment]
除了第二点以外大部分都实现了。
关于 v2 到 v3 的数据迁移以后再搞，我也快开学了

**Comment by g-plane** [comment]
没所谓，话说什么时候发布正式版？另外，方便加个qq或微信吗？（邮件附上）

**Comment by g-plane** [comment]
735715712    微信号也是这个


 

-------- 原始邮件 --------
发件人：printempw <notifications@github.com>
时间：周五 7月29日 15:33
收件人：printempw/blessing-skin-server <blessing-skin-server@noreply.github.com>
抄送：g-plane <g-plane@hotmail.com>,Author <author@noreply.github.com>
主题：Re: [printempw/blessing-skin-server] 对Blessing Skin Server v3的几点建议 (#21)

>除了第二点以外大部分都实现了。 关于 v2 到 v3 的数据迁移以后再搞，我也快开学了 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by prinsss** [comment]
你加我吧，直接搜索这个邮箱就好：h@prinzeugen.net
正式版应该今天会发布

**Comment by g-plane** [comment]
验证问题的答案是什么。问题是干嘛


 

-------- 原始邮件 --------
发件人：printempw <notifications@github.com>
时间：周五 7月29日 15:39
收件人：printempw/blessing-skin-server <blessing-skin-server@noreply.github.com>
抄送：g-plane <g-plane@hotmail.com>,Author <author@noreply.github.com>
主题：Re: [printempw/blessing-skin-server] 对Blessing Skin Server v3的几点建议 (#21)

>你加我吧，直接搜索这个邮箱就好：h@prinzeugen.net 正式版应该今天会发布 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by g-plane** [comment]
求验证问题的答案

**Comment by prinsss** [comment]
那个不是验证问题啦，随便回答就可以的

**Comment by g-plane** [comment]
好吧，我以为是那种答对问题才能加好友的那种

-------- 原始邮件 --------
发件人：printempw notifications@github.com
时间：周五 7月29日 16:04
收件人：printempw/blessing-skin-server blessing-skin-server@noreply.github.com
抄送：g-plane g-plane@hotmail.com,Author author@noreply.github.com
主题：Re: [printempw/blessing-skin-server] 对Blessing Skin Server v3的几点建议 (#21)

> 那个不是验证问题啦，随便回答就可以的 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by g-plane** [comment]
加了吗？


 

-------- 原始邮件 --------
发件人：g-plane <g-plane@hotmail.com>
时间：周五 7月29日 16:05
收件人：printempw/blessing-skin-server <reply@reply.github.com>
主题：Re: [printempw/blessing-skin-server] 对Blessing Skin Server v3的几点建议 (#21)

>好吧，我以为是那种答对问题才能加好友的那种 - 原始邮件 -发件人：printempw <notifications@github.com>时间：周五 7月29日 16:04收件人：printempw/blessing-skin-server <blessing-skin-server@noreply.github.com>抄送：g-plane <g-plane@hotmail.com>,Author <author@noreply.github.com>主题：Re: [printempw/blessing-skin-server] 对Blessing Skin Server v3的几点建议 (#21)那个不是验证问题啦，随便回答就可以的 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
