### ISSUE TITLE
关键文件可被下载

### ISSUE THREAD

**Issue by g-plane** [printempw/blessing-skin-server#22]
储存着相关配置的.env文件能被下载读取。

**Comment by prinsss** [comment]
了解了。
这个应该用 Nginx/Apache 的配置来禁止的，我会把相关配置加上去

**Comment by g-plane** [comment]
好奇一下，为什么不做成像WordPress那样用define呢？

**Comment by prinsss** [comment]
已修复

**Comment by prinsss** [comment]
v2 的时候确实是用 define 的：https://github.com/printempw/blessing-skin-server/blob/v2/config.example.php
但是因为 v3 配置项太多了，全都用常量/变量来配置的话有点蠢，所以就用了 .env 文件
不过我还真没想到这个问题，感谢反馈~
