### ISSUE TITLE
出现了一个错误。。。

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#23]
如题hhhh
<a href="http://mcskin.littleservice.cn">http://mcskin.littleservice.cn</a>麻烦自己看一下
原谅我看不懂OwQ

**Comment by prinsss** [comment]
你把这个文件
`/home/littleqi/domains/littleservice.cn/public_html/mcskin/app/Controllers/HomeController.php`
的第 12 行改成：

```
echo \View::make('index')->with('user', (isset($_SESSION['email']) ? new User($_SESSION['email']) : null))->render();
```

就会有更详细的信息了

**Comment by tnqzh123** [comment]
依然看不懂Orz
原谅我不会PHP

**Comment by tnqzh123** [comment]
好吧是我文件权限设错了Orz
