### ISSUE TITLE
bug json中的skin应该用绝对路径而不是现在这样

### ISSUE THREAD

**Issue by cuteSakuraHime** [printempw/blessing-skin-server#24]
如果请求地址为 /csl 返回 9e78edc7ca41fe0e82b0df143f677d38c98c3014dacbf1c69659827afd3d0fe0
则会访问/csl/textures/9e78edc7ca41fe0e82b0df143f677d38c98c3014dacbf1c69659827afd3d0fe0

会变成404

正确的应该为 https://skin.nyacraft.com/textures/9e78edc7ca41fe0e82b0df143f677d38c98c3014dacbf1c69659827afd3d0fe0

**Comment by prinsss** [comment]
啊对，忘记把 /csl/textures 和 /usm/textures 重写到 /textures 去了
我记得 Custom Skin Loader 不支持绝对路径的

**Comment by cuteSakuraHime** [comment]
应该是支持的，我们是用这种形式实现的
https://skin.moecraft.net/Andy1999.json

**Comment by prinsss** [comment]
不知道 UniSkinMod 支不支持这种相对路径啊，我还是用 rewrite 吧
我去问问 301 管不管用

**Comment by xfl03** [comment]
您以这种方式实现，还不如直接使用传统加载，如果无论有无皮肤/披风都返回一个地址，恐怕部分mod会崩溃。如果您使用CustomSkinLoader来加载您实现的API，恐怕会直接出现材质错误，并且因为您错误不规范实现API，皮肤补丁也不会背锅。

**Comment by xfl03** [comment]
作为CSL作者，在此表态，不会支持您所谓的绝对地址(在json里嵌套传统加载地址)，请您自行rewrite并重定向。

**Comment by cuteSakuraHime** [comment]
你在说什么 听都听不懂
压根没在一个问题上

**Comment by xfl03** [comment]
您好，我是指这个皮肤站的API实现方式不够规范，甚至有可能会引发错误:  
https://skin.moecraft.net/Andy1999.json  
如果这不是您的皮肤站，请您当我什么都没说。

**Comment by cuteSakuraHime** [comment]
我又没用你的Mod

**Comment by prinsss** [comment]
Fixed. https://github.com/printempw/blessing-skin-server/commit/00e03cc99d979f059d17ebe84f12d051058008c5

**Comment by xfl03** [comment]
按照USM的设计原理，所有版本不支持UniSkinAPI中使用绝对路径，1.9之前版本同样会导致渲染错误，部分mod该崩溃也是崩溃(汗..)
不是很懂您的意思

**Comment by xfl03** [comment]
对了，希望您再看一次这个issue，前后矛盾似乎有点严重。

以及"../../skins/xxx"是相对路径，不是绝对路径，看到您的标题抱歉我理解错了。
最后抱歉看到有人不好好实现json API(用json玩传统加载)太激动了，似乎说出了一些过分的话。
