### ISSUE TITLE
建议增加增量更新功能

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#25]
因为我有对代码进行部分修改（主要是展示给用户的文本），然而每次后台升级都会把这些修改还原Orz
所以我提议增加增量更新功能，只下载和替换有变更的文件，同时在后台中展示有变更的文件，这样更方便我修改代码。

**Comment by balthild** [comment]
你可以使用git自行构建

**Comment by prinsss** [comment]
嘛嘛，对于普通用户来说 git 和 gulp 的学习成本也是蛮高的
以后每次更新我都会附上增量更新包的
