### ISSUE TITLE
未安装时访问首页，“安装程序”超链接的HTML代码出错

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#26]
<img src="http://i2.piimg.com/564186/453fc6cee1c0204c.png">
不应该是双引号么。。。

**Comment by prinsss** [comment]
这不是报错，是被转义了。再说单双引号本来都是没差的
话说，我记得我是改成直接跳转而不是提示了啊，你现在是提示没有 textures 文件夹吗

**Comment by tnqzh123** [comment]
刚刚换到3.0.1，的确没有textures文件夹

**Comment by prinsss** [comment]
我知道了，会修复的

**Comment by prinsss** [comment]
等等，我这边 Chrome 测试了没问题啊，你什么浏览器？

**Comment by tnqzh123** [comment]
Chrome 51.0.2704.103

**Comment by prinsss** [comment]
你右键查看源代码，把那一段的内容发来看看

**Comment by tnqzh123** [comment]
早就安装完了。。。还要我把它删掉么Orz

**Comment by prinsss** [comment]
把 textures 文件夹重命名一下就可以看到报错了

**Comment by tnqzh123** [comment]
<a href="http://mcskin.littleservice.cn">http://mcskin.littleservice.cn</a>麻烦自己点进去看下Orz

**Comment by tnqzh123** [comment]
<img src="http://i4.piimg.com/564186/0929525b7beb1eaf.png">

**Comment by prinsss** [comment]
看起来是因为被转义了的关系，但是我这边却不会这样
你是全新安装的吗？
把 /resources/views/errors/e.tpl 的内容发上来看看

**Comment by tnqzh123** [comment]
<img src="http://i4.piimg.com/564186/ca333b02a218fdbe.png">

**Comment by prinsss** [comment]
照理来说应该是这样的：<p>详细信息：{!! $message !!}</p>
你确定是全新安装/覆盖安装的吗？

**Comment by tnqzh123** [comment]
我确定是全新安装。。。

**Comment by prinsss** [comment]
那我就不知道你那边是怎么回事了
你看看 3.0.1 的压缩包里的 /resources/views/errors/e.tpl，和你这个不一样，你这个是旧版的啊

**Comment by tnqzh123** [comment]
好吧Orz
我重下一遍看看

**Comment by tnqzh123** [comment]
真的好灵异Orz
压缩包里的没问题
