### ISSUE TITLE
建议添加是否允许上传披风功能

### ISSUE THREAD

**Issue by ghost** [printempw/blessing-skin-server#3]
披风是一个特别的部位，建议添加一个是否允许上传披风的功能。
即：普通皮肤随意上传，但是披风，必须管理员在后台开启这个功能，或者关闭后只能管理员上传……或者管理员可以指定一个或多个用户，只有指定的用户可以上传披风。

**Comment by prinsss** [comment]
这个。。真的有必要吗？
我可不觉得服主限制披风上传的服务器里有几个人会高兴
