### ISSUE TITLE
v3.0.3 删除材质按钮有bug 数据库有错误

### ISSUE THREAD

**Issue by mhlau233** [printempw/blessing-skin-server#31]
![image](https://cloud.githubusercontent.com/assets/13027589/17965706/c24cbdaa-6a72-11e6-985b-5ad7afc47a11.png)

下面是log
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'tid_steve' at row 1 (SQL: update `players` set `preference` = default, `tid_steve` = , `tid_alex` = , `tid_cape` = , `last_modified` = 2016-08-25 18:19:46 where `pid` = 4) in file /var/www/skin/vendor/illuminate/database/Connection.php on line 713
Stack trace:
1. Illuminate\Database\QueryException->() /var/www/skin/vendor/illuminate/database/Connection.php:713
2. PDOException->() /var/www/skin/vendor/illuminate/database/Connection.php:464
3. PDOStatement->execute() /var/www/skin/vendor/illuminate/database/Connection.php:464
4. Illuminate\Database\Connection->Illuminate\Database{closure}() /var/www/skin/vendor/illuminate/database/Connection.php:706
5. Illuminate\Database\Connection->runQueryCallback() /var/www/skin/vendor/illuminate/database/Connection.php:669
6. Illuminate\Database\Connection->run() /var/www/skin/vendor/illuminate/database/Connection.php:467
7. Illuminate\Database\Connection->affectingStatement() /var/www/skin/vendor/illuminate/database/Connection.php:410
8. Illuminate\Database\Connection->update() /var/www/skin/vendor/illuminate/database/Query/Builder.php:2072
9. Illuminate\Database\Query\Builder->update() /var/www/skin/vendor/illuminate/database/Eloquent/Builder.php:531
10. Illuminate\Database\Eloquent\Builder->update() /var/www/skin/vendor/illuminate/database/Eloquent/Model.php:1551
11. Illuminate\Database\Eloquent\Model->performUpdate() /var/www/skin/vendor/illuminate/database/Eloquent/Model.php:1470
12. Illuminate\Database\Eloquent\Model->save() /var/www/skin/app/Controllers/PlayerController.php:141
13. App\Controllers\PlayerController->clearTexture() /var/www/skin/vendor/pecee/simple-router/src/Pecee/SimpleRouter/RouterEntry.php:377
14. call_user_func_array() /var/www/skin/vendor/pecee/simple-router/src/Pecee/SimpleRouter/RouterEntry.php:377
15. Pecee\SimpleRouter\RouterEntry->renderRoute() /var/www/skin/vendor/pecee/simple-router/src/Pecee/SimpleRouter/RouterBase.php:163
16. Pecee\SimpleRouter\RouterBase->routeRequest() /var/www/skin/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php:22
17. Pecee\SimpleRouter\SimpleRouter->start() /var/www/skin/app/Services/Boot.php:121
18. App\Services\Boot->bootRouter() /var/www/skin/app/Services/Application.php:39
19. App\Services\Application->run() /var/www/skin/index.php:16

**Comment by mhlau233** [comment]
![image](https://cloud.githubusercontent.com/assets/13027589/17965746/f9fc9536-6a72-11e6-96b5-5f5fcd9173c0.png)

**Comment by prinsss** [comment]
感谢反馈，下个版本会修复

**Comment by mhlau233** [comment]
@printempw   额还有SMTP也是用不了窝0.0

**Comment by prinsss** [comment]
SMTP 用不了？具体什么情况？

**Comment by prinsss** [comment]
已经修复。
话说明明我本地环境没有问题的，应该是你的数据库开了 Strict Mode 吧。
