### ISSUE TITLE
检查更新页面出现错误

### ISSUE THREAD

**Issue by zzyyuanmi** [printempw/blessing-skin-server#32]
检查更新 Check Update

Notice: 出现了一些错误

详细信息：Undefined index: github

文件位置：/home/wwwroot/skin/app/Services/Updater.php: 55

**Comment by prinsss** [comment]
当前版本？
是从什么版本升级上来的吗？

**Comment by zzyyuanmi** [comment]
v3.0.4 全新安装的

**Comment by prinsss** [comment]
嗯，这是我的锅，我忘记改了，下个版本会修复。
临时解决方法：把 数据库中 options 表里的 update_source 记录的值从 `github` 改为 `nyavm`。

**Comment by zzyyuanmi** [comment]
嗯，我用 `error_reporting = E_ALL & ~E_NOTICE` 忽略报错了
