### ISSUE TITLE
关于皮肤与数据库的问题

### ISSUE THREAD

**Issue by Achang233** [printempw/blessing-skin-server#33]
比较急！懒得用英文了。这个问题不算太严重，如果你把皮肤站目录下缓存的皮肤删掉，那么皮肤站上就会出现一些有趣的问题，可以仔细看看！

**Comment by prinsss** [comment]
缓存的皮肤？你用的是什么版本？
在未发布的 v3.1 之前是没有皮肤的缓存机制的啊
你不会说的是 textures 文件夹下的那些东西吧？

**Comment by Achang233** [comment]
哎呀！大大来了！对，就是那些东西，我用的V3.4 （暂时还在单机与宿舍里的小伙伴用，并没有公开）没错就是texture

**Comment by prinsss** [comment]
诶哟我滴妈
`textures` 里存的就是皮肤源文件，不是缓存啊。所有皮肤文件的请求底层都是读取的这些东西，你删掉当然会出问题
不要看到文件名是一大串字符就觉得是缓存啊我的朋友

**Comment by Achang233** [comment]
好吧，我的锅
