### ISSUE TITLE
演示站删除账号报错

### ISSUE THREAD

**Issue by AsakuraFuuko** [printempw/blessing-skin-server#37]
> Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App\Models\DB' not found in file /home/wwwroot/skin.prinzeugen.net/app/Models/User.php on line 259
> Stack trace:
> 1. Symfony\Component\Debug\Exception\FatalThrowableError->() /home/wwwroot/skin.prinzeugen.net/app/Models/User.php:259

**Comment by prinsss** [comment]
哦这是旧版的 bug，目前最新的版本（v3.2 pr4）已经修复过这个问题了，演示站还停留在 v3.1.2 没更新
