### ISSUE TITLE
目录权限问题

### ISSUE THREAD

**Issue by ghost** [printempw/blessing-skin-server#38]
我把所有的文件传到虚拟主机，然后就没法删除了。最后找来找去，是这个目录：
blessing-skin-server-v3.1.2\vendor\symfony\finder\Tests\Fixtures\r+e.gex[c]a(r)s\dir
的问题（其实还有好几个，我只是列出最典型的一个）。
最后解决的办法是设定目录权限为所有权限。

那么问题来了，这个如此奇怪的目录到底是干啥用的？。。。另外还有好几个目录存在问题，都是那种看起来很奇怪的。我删除了这些目录，也并没有啥问题出现啊。。。那为什么压缩包中如此多莫名其妙的目录呢？是不是应该注意一下这个问题呢？

**Comment by prinsss** [comment]
这些是 Symfony 组件里的东西，因为框架使用了一些 Symfony 框架的组件，引用依赖的同时可能也会有一些**没用到**的文件被一起放入了 vendor 库目录里（这就是为什么你删掉那些还可以正常使用的原因）

**但是**，因为我是使用 composer 来统一管理依赖的，所以没法把发布的「已经把依赖库文件打包进去的压缩包」中的那些无用文件删除。

至于你说的导致无法删除的目录权限问题并不是那些奇怪的文件的问题吧？因为我这边删除（目录所有权限正确）是没有任何问题的

**Comment by printempw** [comment]
这些是 Symfony 组件里的东西，因为框架使用了一些 Symfony 框架的组件，引用依赖的同时可能也会有一些**没用到**的文件被一起放入了 vendor 库目录里（这就是为什么你删掉那些还可以正常使用的原因）

**但是**，因为我是使用 composer 来统一管理依赖的，所以没法把发布的「已经把依赖库文件打包进去的压缩包」中的那些无用文件删除。

至于你说的导致无法删除的目录权限问题并不是那些奇怪的文件的问题吧？因为我这边删除（目录所有权限正确）是没有任何问题的

**Comment by ghost** [comment]
@printempw 看起来是压缩包的问题。不知道为何从 GitHub 直接下载的 ZIP 压缩文件，直接传到虚拟主机解压会……出现这种莫名其妙的问题。我自己先解压再次打包上传就没有任何问题了。。。。。。。。真莫名其妙。。。
不过好歹知道怎么解决了。
