### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by MlgmXyysd** [printempw/blessing-skin-server#4]
Warning: mysqli::mysqli() expects parameter 5 to be long, string given in /home/u185635302/public_html/Skins/admin/install.php on line 54

Warning: mysqli::query(): Couldn't fetch mysqli in /home/u185635302/public_html/Skins/includes/Database.class.php on line 38

Warning: mysqli::query(): Couldn't fetch mysqli in /home/u185635302/public_html/Skins/admin/install.php on line 156

数据表创建失败
照理来说不应该的，请带上错误信息联系作者：

Warning: main(): Couldn't fetch mysqli in /home/u185635302/public_html/Skins/admin/install.php on line 159

**Comment by prinsss** [comment]
把你的 config.php 贴出来

**Comment by MlgmXyysd** [comment]
麻烦能去掉MYSQL的端口吗，主机的mysql地址没有端口

**Comment by prinsss** [comment]
咦？主机的 mysql 地址没有端口是什么意思，所有的 MySQL 服务器不都应该有端口吗？默认 3306 的
