### ISSUE TITLE
不支持的加密方式

### ISSUE THREAD

**Issue by ghost** [printempw/blessing-skin-server#43]
https://github.com/printempw/blessing-skin-server/wiki/Introduction-of-fields-in-.env
在这个Wiki文档中提到：
PWD_METHOD 用户密码加密方式，可选的值有 MD5, SALTED2MD5, SHA256, SHA512, SALTED2SHA256, SALTED2SHA512

可是除了MD5, SALTED2MD5, SHA256外，SHA512, SALTED2SHA256, SALTED2SHA512这三个根本就不支持。请问这是我环境的问题还是………………

（各种强迫症，看到MD5内心就感到不安全的颤抖……）

**Comment by prinsss** [comment]
我刚刚测试了，并没有问题啊
你用的哪个版本？报什么错？

**Comment by ghost** [comment]
3.1.2 版本，会提示严重错误：
```
Symfony\Component\Debug\Exception\FatalErrorException: Class 'App\Services\Cipher\SALTED2SHA512' not found in file ..................
```

**Comment by prinsss** [comment]
唔，你应该用的是 v3.1.2 吧，这些新的加密方式是 v3.2 才支持的
那篇 Wiki 上写的是 v3.2 测试版的情况，抱歉
等下我就会发布 v3.2 了

**Comment by ghost** [comment]
好的，没关系，我就猜测是因为版本旧的缘故……

**Comment by prinsss** [comment]
v3.2 已发布，试试看吧~
https://github.com/printempw/blessing-skin-server/releases
