### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by TResult97** [printempw/blessing-skin-server#46]
![image](https://cloud.githubusercontent.com/assets/13347605/21743939/5396f228-d547-11e6-80fe-8bfecb2c65c2.png)
![image](https://cloud.githubusercontent.com/assets/13347605/21743950/6fd3f602-d547-11e6-951f-5ba5e11b5136.png)
![image](https://cloud.githubusercontent.com/assets/13347605/21743956/805d4366-d547-11e6-8090-ff4ae24405db.png)
如图所示，这些图片都无法正常显示
访问https://skin.jiangzimc.cn/char_Fz.json可以得到
`{
    "username": "char_Fz",
    "skins": {
        "default": "10df799a2a8a4effd9c7740e132c141f7032f77021a3710a1e9fe2e7320a6d7f",
        "slim": null
    },
    "cape": null
}`
访问skin.jiangzimc.cn/skin/char_Fz.png无法获得皮肤
![image](https://cloud.githubusercontent.com/assets/13347605/21744017/e31c05a4-d548-11e6-923f-d2036ecb6f18.png)

**Comment by prinsss** [comment]
请检查你的 Nginx 规则配置中是否有其他匹配 png的（通常这类规则被用于控制浏览器缓存）

这类规则一般长这样：
```
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
    expires 30d;
    access_log off;
}
```

如果你的 Nginx 配置中存在这样的规则，请删去其中匹配 `png` 的表达式。

**Comment by TResult97** [comment]
实在是没想到那么晚了还会得到回复，十分感谢，问题已经解决了：）
