### ISSUE TITLE
老用户绑定邮箱出bug

### ISSUE THREAD

**Issue by refparo** [printempw/blessing-skin-server#47]
![default](https://cloud.githubusercontent.com/assets/13145126/22181840/f8cb7564-e0cf-11e6-9b7c-4dd69f1c82aa.png)
输入邮箱后点绑定就这样了
![default](https://cloud.githubusercontent.com/assets/13145126/22181844/0e63f540-e0d0-11e6-8473-480a0c6234e4.png)

**Comment by prinsss** [comment]
应该已经修复了，去演示站再绑定看看？

**Comment by refparo** [comment]
可以了

**Comment by prinsss** [comment]
嗯，感谢反馈 👍
