### ISSUE TITLE
“我的衣柜”中点击“在皮肤库中查看”链接到的 url 错误

### ISSUE THREAD

**Issue by refparo** [printempw/blessing-skin-server#48]
又是一个小问题 :joy:
![default](https://cloud.githubusercontent.com/assets/13145126/22181932/9dc68b38-e0d2-11e6-9191-ca9adb8c6d32.png)
这个按钮链接到的 url 是 `http://123.57.132.134/skinlib/show?tid=xxxx`，正确的 url 是 `http://123.57.132.134/skinlib/show/xxxx`

**Comment by prinsss** [comment]
感谢反馈，已经修复（今早改路由的漏网之鱼）
