### ISSUE TITLE
建议添加一功能

### ISSUE THREAD

**Issue by g-plane** [printempw/blessing-skin-server#5]
发现它没有“忘记密码”的功能。另外可以考虑加入“在线更新”的功能（像WordPress那样）。

**Comment by prinsss** [comment]
在线更新暂时不考虑
忘记密码的话有点麻烦，因为我没有记录邮箱之类的信息
我原本是定位的服务器皮肤站，所以忘记的话去找腐竹吧，后台可以改密码的
