### ISSUE TITLE
细节问题

### ISSUE THREAD

**Issue by g-plane** [printempw/blessing-skin-server#50]
- 管理面板中“角色管理”页面，点击“预览材质”还是会跳转到旧版的 URL，即 `skinlib/show?tid=`
- “我的衣柜”中，没有直接点击材质，只是点击材质下方的齿轮，就触发了 `MSP.changeSkin()` 或 `MSP.changeCape()`
 - “用户中心”中的“角色管理”页面没有使用 `@include('vendor.texture-preview')`

**Comment by prinsss** [comment]
1. 已记录
2. 因为 DOM 事件有冒泡机制，点击齿轮的事件被父元素捕捉到了。已记录。
3. 因为角色管理页做了一些改动，下次看看是否有更好的方法实现代码复用

**Comment by g-plane** [comment]
是因为要切换 2D/3D 预览吗？

**Comment by prinsss** [comment]
是。
初步打算用模板继承实现复用，顺便重新组织下 views/vendor 的内容。

**Comment by g-plane** [comment]
能不能对于 3D 部分使用 `@include`，2D 依旧，但分成两个 div，通过增删 `hidden` 的 class 来控制显示？

**Comment by prinsss** [comment]
也行，我到时候再看看

**Comment by g-plane** [comment]
还有三个细节：
- “上传材质”页面，第一次从本地选择了材质文件后（但没有上传），自动以材质文件名填上了“材质名称”的输入框，接着重新从本地选择材质文件（没有刷新页面），此时“材质名称”的输入框还是保留了第一次的文件名，而不是最后一次的。
- "我的衣柜"页面，一旦材质列表换页，右方的预览就刷新了（出现这个现象是因为换页依靠更新 Query String 实现的吧？）
- 也正因为上面一点，当皮肤的页数不等于披风的页数时，如果当前页数过大，会导致皮肤或披风页提示“衣柜里啥都没有哦”

这些只是无关紧要的细节，学习任务繁重的话，可以先把这些问题放在一边

**Comment by prinsss** [comment]
1. 虽然之前发现了但是当时懒得改……总之已记录
2. 材质列表换页的话是靠直接刷新页面实现的，我的衣柜那边并没有做任何 AJAX 处理（还是懒
3. 同上，因为懒把皮肤和披风的分页做一起了

我的衣柜 / 皮肤库的分页初步打算在下个版本使用 `jqPaginator` 等分页库实现。

**Comment by g-plane** [comment]
假设某个材质一开始是公开材质，然后有非上传者使用了这个材质，接着上传者把这个材质设为隐私，但这个非上传者还是能使用这个材质。这样会不会不太好？

**Comment by prinsss** [comment]
嗯？我记得当「用户访问衣柜」的时候会自动把「失效材质」（被删除或被设为隐私）从衣柜中删去的啊

**Comment by prinsss** [comment]
看来只自动去除了被删掉的材质。。OK，已记录
https://github.com/printempw/blessing-skin-server/blob/master/app/Models/Closet.php#L74

**Comment by g-plane** [comment]
呃，衣柜反而没注意到。我的意思是那个非上传者已经使用了那个材质（即一开始是公开，后来改为隐私的）

**Comment by prinsss** [comment]
哦，你说这个啊。也是，到时候一起加
