### ISSUE TITLE
大神。。披风渲染是不是有点问题

### ISSUE THREAD

**Issue by Curtain2312** [printempw/blessing-skin-server#52]
披风上传后 貌似被当成皮肤贴图一样渲染到了披风上。。。请大神检查看下

**Comment by prinsss** [comment]
为何关闭了此 issue？问题解决了吗？

你所描述的问题是发生在「皮肤 3D 预览上吗」？你点「浏览」选择完文件之后选择了「材质类型」处选择了「披风」吗？
