### ISSUE TITLE
使用数据库对接DISCUZ后无法登陆

### ISSUE THREAD

**Issue by Colinwood11** [printempw/blessing-skin-server#53]
请原谅我进不去后台找插件商店的作者
显示密码错误，然而我密码与DISCUZ的密码是一样的

**Comment by g-plane** [comment]
您所说的“密码错误”指的是登录皮肤站时显示密码错误还是数据库连接错误？

**Comment by prinsss** [comment]
1. 检查皮肤站 `.env` 中填写的「加密方式」是否正确（Discuz 一般为 `SALTED2MD5`）
2. 检查 Discuz 论坛（非皮肤站）能否登录
3. 在皮肤站新注册用户，登出后检测能否再次登录
4. Discuz 新建用户，使用同样的邮箱和密码在皮肤站登录，观察室提示「密码不正确」还是「用户不存在」
5. 在数据库 `options` 表中将 `da_verbose_log` 项的值改为 `true` 以开启详细日志记录
6. 开启日志记录后，尝试登录皮肤站，然后将位于 `storage/logs/laravel.log` 的日志文件发送给我

**Comment by Colinwood11** [comment]
显示  邮箱或密码不对哦~   加密方式正确，Discuz可以登录。

**Comment by prinsss** [comment]
OK，尝试登录一次后提供日志吧
发送到 h#prinzeugen.net（# 换成 @）或者其他你方便的方式

**Comment by Colinwood11** [comment]
Discuz可以登录，皮肤站点登录显示邮箱或者密码不正确，log文件稍后到达

**Comment by prinsss** [comment]
日志文件已收到
请去 Discuz 数据库的 `pre_ucenter_members` 查看你所尝试登录的那个账号的记录，看看 `salt` 字段有没有内容
最好把那一条记录的内容都贴上来

**Comment by Colinwood11** [comment]
我需要使用的表是pre_ucenter_members？

**Comment by prinsss** [comment]
是的，在 `pre_ucenter_members` 中找出你所使用的用户的那一行记录，看看 salt 字段有没有内容
最好把那一条记录的内容都贴上来

**Comment by Colinwood11** [comment]
之前我设置的是pre com* menbers的表。。我先改回来测试下

**Comment by prinsss** [comment]
果然，我知道是为什么了
虽然这两个表都保存了用户信息，但是 `salt` 字段值只存在于 `pre_ucenter_members` 表里
登录皮肤站时数据对接插件会去你设置的那个数据表里查询用户信息和 `salt`，盐值不正确将会造成无法登录

**Comment by Colinwood11** [comment]
对，不过多谢了这次  让我查到了我的`menbers`表有错误可以修复。

麻烦在插件内写清楚使用的是`pre_ucenter_members`表，或者说，选择discuz对接方式后，如果输入框为空，自动自动填入pre_ucenter_members。

如果还有用户遇到我这样的情况，无法登录后台可以进入【*皮肤站*】的数据库中找到`options`表  进入`da_connection`表中查找

> "table";s:19:"pre_common_member";}
`将pre_common_member改为pre_ucenter_members`即可

**Comment by prinsss** [comment]
我在 Wiki 里有写清楚了啊：[数据库连接配置](https://github.com/printempw/blessing-skin-server/wiki/%E5%A6%82%E4%BD%95%E5%A1%AB%E5%86%99%E6%95%B0%E6%8D%AE%E5%AF%B9%E6%8E%A5%E9%85%8D%E7%BD%AE#%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%9E%E6%8E%A5%E9%85%8D%E7%BD%AE)，插件配置里也有到这个页面的链接……

总之解决了就好 ;)
