### ISSUE TITLE
演示站boom了

### ISSUE THREAD

**Issue by AsakuraFuuko** [printempw/blessing-skin-server#54]
OOM command not allowed when used memory > 'maxmemory'.

如果您是访客，这说明网站程序出现了一些错误，请您稍后再试或联系站长。
如果您是站长，请开启 .env 中的 APP_DEBUG 以查看详细信息。

**Comment by prinsss** [comment]
什么时候、什么操作下出现的呢？
我刚才访问了一下，似乎没什么问题

**Comment by prinsss** [comment]
OK，似乎是 Redis 的缓存大小达到了最大内存限制。
我调整了一下，现在应该没问题了 :D
