### ISSUE TITLE
缓存失效时间修改不回来

### ISSUE THREAD

**Issue by hzykj** [printempw/blessing-skin-server#56]
前天手贱把缓存失效时间改成了31536000，现在修改为10，但是页面返回的数据任然显示max-age=31536000, public
这个如何解决？这算不算bug？

**Comment by hzykj** [comment]
CDN都关了，网页服务器也重启了，本地缓存也清空了

**Comment by prinsss** [comment]
咦？在我这边访问时响应头中显示的是 `Cache-Control:max-age=10, public` 哦？
![20170418220022.png](https://img.blessing.studio/images/2017/04/18/20170418220022.png)

**Comment by prinsss** [comment]
你可以在 URL 后面加上类似 `?test=123` 这样的随机 Query String 以防止缓存干扰

**Comment by hzykj** [comment]
好的，还有个问题就是那个从角色管理页面点击那个预览图进的皮肤页面显示404

**Comment by hzykj** [comment]
是管理面板里的

**Comment by prinsss** [comment]
哦哦，那个是 BUG，之前就已经记录过了
不过我现在高三学业很紧张，这样优先级低的 BUG 就先放一放，以后有时间了再更新修复
见谅啦 😄

**Comment by hzykj** [comment]
恩恩，辛苦了
那个材质删除以后，原来的使用者仍然能够使用（准确的说应该是任然显示加载过材质，但是材质文件已经删除），希望大大高考结束后能够进行修复

**Comment by hzykj** [comment]
再次感谢你给我们带来的这个高端漂亮的皮肤站

**Comment by prinsss** [comment]
好的~
