### ISSUE TITLE
无法加载图片

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#57]
用 OneinStack 部署的 LNMP 环境，按照[https://github.com/printempw/blessing-skin-server/issues/46](url)中说的把虚拟主机配置文件和 nginx.conf 里关于缓存的那部分配置都删除了也重载了，但是仍无法正常加载图片，Console 和 Nginx 的日志文件都显示 404 。
<img src="https://www.littleqiu.net/wp-content/uploads/2017/04/QQ截图20170419215039.png" />
<img src="https://www.littleqiu.net/wp-content/uploads/2017/04/QQ图片20170419214914.png" />
<img src="https://www.littleqiu.net/wp-content/uploads/2017/04/QQ图片20170419214930.png" />

**Comment by prinsss** [comment]
在新标签页打开这个图片，看看是什么样的 404 页面？

如果是 Nginx 默认的 404 页面，就说明是伪静态没配置好，请求没有移交给皮肤站处理

**Comment by tnqzh123** [comment]
的确是 Nginx 的 404 页面
但是皮肤站其他页面可以正常访问啊...
能帮我看看吗 Orz...
![qq 20170420201640](https://cloud.githubusercontent.com/assets/16630630/25230396/5277b9da-2606-11e7-914e-3eb961c39bfd.png)

**Comment by g-plane** [comment]
你设置了 Referer 限制，皮肤 Mod 会获取不了皮肤的吧？

**Comment by prinsss** [comment]
就是设置 referers 那块的问题。

那一块的规则优先级更高，`*.png` 被匹配到了那一块去。和缓存那个一个道理
改的方法也一样。

**Comment by prinsss** [comment]
毕竟主要的原因是有更高优先级的匹配规则导致请求没有交由皮肤站处理，和规则是缓存用的还是防盗链用的没关系

**Comment by tnqzh123** [comment]
了解了，感谢
