### ISSUE TITLE
能魔改吗……

### ISSUE THREAD

**Issue by sakurayang** [printempw/blessing-skin-server#60]
![sp170423_165640](https://cloud.githubusercontent.com/assets/11017232/25312223/52fe0976-2846-11e7-80cf-3211d0dc0c8c.png)

绝对不是浏览器问题
嘛……从v2升v3就这样啦……
然后进/setup说已安装
然后点下一步
`escapeshellarg() has been disabled for security reasons`

但是用v2又有个提示……强迫症表示好闹心

**Comment by prinsss** [comment]
这是样式没加载出来啊……正常的安装页面可不是这样的
按 F12 看看有没有报错

**Comment by sakurayang** [comment]
给你两个地址……一个是v2升v3的
一个是v3的
.env都正确配置了的
phpinfo在resourse.acgcode.ml/1.php

v2->v3 skin.acgcode.ml
v3 resourse.acgcode.ml  

你看一下吧，v3会是500

**Comment by sakurayang** [comment]
v2升v3的可以进/admin
但是主页和功能和v2一毛一样

**Comment by prinsss** [comment]
我看你 `skin.acgcode.ml` 的页面有个超大的劫持广告……你加的？
你也没给我【v2 升级至 v3】时的页面啊
v3 500 那个请先阅读 [常见问题 FAQ](https://github.com/printempw/blessing-skin-server/wiki/FAQ#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8F%AA%E6%98%BE%E7%A4%BA-500-%E9%94%99%E8%AF%AF%E6%B2%A1%E6%9C%89%E8%AF%A6%E7%BB%86%E6%8A%A5%E9%94%99)。

![屏幕截图(182).png](https://ooo.0o0.ooo/2017/04/24/58fe07492d89b.png)

**Comment by sakurayang** [comment]
关于广告……主机商的……
v3的500我已经看过F&Q，绝对
v2升v3的……升级时502……
你可以试试用user: Gerard与pass:   12shf1进去
还有就是 升级在这==>[http://skin.acgcode.ml/index.php/setup](http://skin.acgcode.ml/index.php/setup)

**Comment by prinsss** [comment]
淦，你这明显是因为主机商的广告劫持导致安装页面加载失败啊！！
换主机或者上 HTTPS 吧，不然我也没辙。
