### ISSUE TITLE
启用数据对接后就无法再后台更改玩家角色的用户名与昵称？

### ISSUE THREAD

**Issue by Colinwood11** [printempw/blessing-skin-server#61]
是故意为之还是代码错误？

**Comment by tnqzh123** [comment]
如果你说的是玩家的用户中心的话，故意为之，这个群里讨论过，涉及到封禁之类的东西。
如果你说的是管理员的管理面板，貌似本来就不能改吧？

**Comment by Colinwood11** [comment]
后台用户管理，更改昵称。 更改后  用户刷新还是干嘛  过一会会自动恢复成原来的昵称。直接去MYSQL改的话    也会过一会就恢复

**Comment by prinsss** [comment]
有意而为之。

如果你在插件配置中「重复处理」选择的是「用目标程序上的用户数据覆盖皮肤站」的话，那么【皮肤站】上用户的【昵称】会被自动同步为该用户在【目标程序】上具有【相同邮箱】账户的【用户名】

不愿意这样的话，请同时更改数据对接【目标程序】上的用户名或修改数据对接插件的「重复处理」配置项。

**Comment by Colinwood11** [comment]
OK。那么能不能支持后台更改玩家的角色名字呢？

**Comment by prinsss** [comment]
哦哟，你这样一说确实没有这个功能，毕竟原本是「单账户多角色」制的嘛
你可以把旧角色删掉，新建个角色，然后指派给该用户

我会考虑给开启数据对接后的后台加上「修改玩家角色名」功能

**Comment by g-plane** [comment]
好像不使用数据对接，后台的管理面板也不能修改角色名吧？
