### ISSUE TITLE
一些感觉是 Bug 的地方

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#62]
第一个是用户中心首页，启用数据对接插件后虽然 "角色管理" 页面内不能再新建角色了，但是用户中心首页依然会显示用户的可创建角色总数，而且我好像也没有在管理面板找到关于这个的设置项...
![qq 20170423215059](https://cloud.githubusercontent.com/assets/16630630/25314068/02e2dbfa-286f-11e7-8b36-8af5054af1ef.png)
第二个是 "角色管理" 页面，一样在启用了数据对接插件的情况下，无法预览材质。
![qq 20170423215235](https://cloud.githubusercontent.com/assets/16630630/25314073/3ae2b03e-286f-11e7-9fec-c8d2a0338089.png)
![qq 20170423215245](https://cloud.githubusercontent.com/assets/16630630/25314075/3e07ed7e-286f-11e7-83d1-e4bf808e7d4b.png)
而且默认是 3D 预览，但是实际上展示的是 2D 预览...
![qq 20170423215418](https://cloud.githubusercontent.com/assets/16630630/25314083/7094c5be-286f-11e7-9c22-ef776f5cc968.png)
暂时就找到了这俩，程序版本是 3.2.1 。顺便问下这里的文本要在哪里改，我用 Notepad++ 搜了一下貌似找不到...
![qq 20170423215528](https://cloud.githubusercontent.com/assets/16630630/25314092/967f5154-286f-11e7-9487-b0afc55a793a.png)

**Comment by g-plane** [comment]
之所以出现第一点那种情况，是因为数据对接插件不会干预用户中心的仪表盘。

**Comment by prinsss** [comment]
1. 那个「使用情况」完全是按照当前积分和角色/存储价格来算的，确实老是被人吐槽，以后改改吧
2. 关于这个问题，先按 F12 看看有没有报错？这个角色是确实有皮肤/披风的吗？（数据库中是否有相应记录）
3. 在数据对接插件的 [`data-integration/views/player.tpl`](https://coding.net/u/printempw/p/blessing-skin-plugins/git/blob/master/data-integration/views/player.tpl#L72) 这里哦

**Comment by tnqzh123** [comment]
1.了解了
2.确实 Console 有报错，全文如下
![1](https://cloud.githubusercontent.com/assets/16630630/25383171/76a76d06-29ed-11e7-8c55-95085cb0b38e.png)
不知道是不是又是伪静态或者缓存的问题，但是 Nginx 的配置文件里除了伪静态和 .env 的保护之外就只有 SSL 、日志和 FastCGI 的配置了...伪静态和保护 .env 的相关内容直接复制 Wiki 里的...
数据库中确实有相关记录，也能正常返回角色的 json ，是有对应材质的记录的。
3.了解了，感谢

**Comment by prinsss** [comment]
这个报错说明 3D 预览库没加载出来啊（404）
你确定那个文件存在吗

**Comment by tnqzh123** [comment]
确定这个文件存在（吧），而且皮肤库和我的衣柜都能正常用 3D  预览
![qq 20170426211111](https://cloud.githubusercontent.com/assets/16630630/25436165/0e876bc6-2ac5-11e7-9a27-edca397c1bc5.png)

**Comment by prinsss** [comment]
哦，你启用了数据对接插件吧？

应该是数据对接插件的 BUG，临时解决方法：定位至 `data-integration/views/player.tpl` 第 `115` 行，将：
```
<script type="text/javascript" src="{{ assets('dist/libs/three.min.js') }}"></script>
<script type="text/javascript" src="{{ assets('dist/libs/three.msp.js') }}"></script>
```
修改为：
```
<script type="text/javascript" src="{{assets('scripts/three.min.js') }}"></script>
<script type="text/javascript" src="{{assets('scripts/three.msp.js') }}"></script>
```

**Comment by tnqzh123** [comment]
已解决，感谢

**Comment by prinsss** [comment]
已修复。https://coding.net/u/printempw/p/blessing-skin-plugins/git/commit/14aed87d1f349c54e45bfde6f40e5c71a4296507
