### ISSUE TITLE
对接authlib-agent

### ISSUE THREAD

**Issue by l89669** [printempw/blessing-skin-server#65]
脑洞大开QwQ
https://github.com/to2mbn/authlib-agent

**Comment by prinsss** [comment]
这个项目看起来很有意思 :D
高考完后，我会尝试搞一个支持 Yggdrasil API 的皮肤站插件 ;)

**Comment by l89669** [comment]
umm... 高考完后好久了
等你的插件哦

**Comment by prinsss** [comment]
正在考虑志愿的事情，之后再说吧

**Comment by l89669** [comment]
好吧
祝早日收到理想院校的录取通知书

**Comment by prinsss** [comment]
谢谢 :)

**Comment by prinsss** [comment]
你现在是否仍有让皮肤站提供 Yggdrasil API 的需求？如果是，请回复此 issue，我会在最近几天抽空写个插件

**Comment by tnqzh123** [comment]
hmm 表示我有 Orz

**Comment by l89669** [comment]
有，非常迫切QwQ

**Comment by prinsss** [comment]
WIP

![project](https://i.loli.net/2017/07/27/5979a3e35e9db.png)

**Comment by l89669** [comment]
Thanks

**Comment by prinsss** [comment]
插件主体已经写好，希望你能帮忙测试。

插件源码：https://coding.net/u/printempw/p/blessing-skin-plugins/git/tree/master/yggdrasil-api
插件打包下载：https://coding.net/u/printempw/p/blessing-skin-plugins/git/blob/master/dist/yggdrasil-api_v1.0.zip

**Comment by tnqzh123** [comment]
实测用户存在但返回 No such user
![tim 20170729115031](https://user-images.githubusercontent.com/16630630/28741926-2a28b8e8-7454-11e7-91fa-fcc22798c646.png)

**Comment by prinsss** [comment]
哎呀，忘记 Yggdrasil API 登录时的 username 是邮箱了，被 wiki 摆了一道

下午修复吧，既然是用邮箱登录那就好办了，可以实现单邮箱多用户选择界面了。

**Comment by l89669** [comment]
@Minecraft-LittleQiu 你搭建的地址是什么，方便让我测试一下吗？

**Comment by tnqzh123** [comment]
@l89669 https://mcskin.littleservice.cn ，欢迎使用 LittleSkin~

**Comment by l89669** [comment]
@printempw 我想请问一下这个插件是能实现皮肤站注册用户时与authlibagent的数据库自动对接吗？还是只实现皮肤互通？

**Comment by l89669** [comment]
看了一下项目介绍。。。你好像是直接重新写了authlib-agent的服务端部分？

**Comment by prinsss** [comment]
可以用皮肤站的邮箱 / 密码来登录，还能选择角色

![1](https://i.loli.net/2017/07/29/597c4110518f0.png)
![2](https://i.loli.net/2017/07/29/597c41108a7c7.png)

**Comment by prinsss** [comment]
是啊，和 authlib-agent 的服务端一样，我是用插件实现了完整的 Yggdrasil API

**Comment by l89669** [comment]
非常感谢大佬的辛苦劳动。。。（不过总感觉authlib-agent的作者会不爽。。。）

**Comment by prinsss** [comment]
人家都把 authlib-javaagent 和服务端开源出来了，不至于那么小肚鸡肠的

**Comment by tnqzh123** [comment]
所以说这个版本稳定了吗...我有点急着用，因为我服的登陆插件在密码上出了点偏差...

**Comment by prinsss** [comment]
你说这个插件？不稳定，还没调试好呢，大概也许晚上能好吧

**Comment by l89669** [comment]
authlib-agent编译好的jar直接可以拿来用吗？还是还需要重新合插件配合编译一遍？
我看着jar里有证书，但是插件里并没有（没看出来证书是干什么用的）
又看了一下，证书是公钥，所以对应的服务端里应该要有一个私钥吧。。。

**Comment by tnqzh123** [comment]
如果编译的时候设置的服务端 API 地址和皮肤站插件的没区别的话，应该是可以直接用的。

**Comment by prinsss** [comment]
需要修改 `configure.sh` 中的 `AGENT_API_ROOT` 和 `AGENT_SKIN_DOMAINS`，改成你自己的 API 地址。

**Comment by l89669** [comment]
api地址编译后也可以改的，改里面的配置文件就可以了，如果只需要改地址，完全不用重新编译

**Comment by l89669** [comment]
所以那个公钥证书是干什么用的。。。好像跟服务端完全没有关系的样子

**Comment by prinsss** [comment]
给 textures 签名用的

**Comment by l89669** [comment]
不懂。萌新我现在只会写写插件mod什么的

**Comment by l89669** [comment]
顺便问一句。。。bless支持中文的角色名吗？

**Comment by tnqzh123** [comment]
滋磁，只需要在管理面板中开启相关设置项即可。

**Comment by prinsss** [comment]
后台可以修改支持或是不支持的啊

**Comment by l89669** [comment]
谢谢回答~

**Comment by prinsss** [comment]
我这边测试了 OK 了，BETA2 版的插件打包可在这里下载：https://mega.nz/#!3hwkDIgZ!_MbIYFvWAwo26M0r1qVQrhkxdiskJUq8pXVqsPQDVWo

期待你的反馈。

![1](https://i.loli.net/2017/07/29/597c761500c7b.png)
![2](https://i.loli.net/2017/07/29/597c7615c4534.png)

**Comment by tnqzh123** [comment]
HMCL 报用户名或密码错误，但是用户名和密码应该没错的。皮肤站密码加密方式 SALTED2MD5，盐值是在安装时自动生成的共 32 位。
![tim 20170729200844](https://user-images.githubusercontent.com/16630630/28744732-c1146802-7499-11e7-9617-ce2c713fceb1.png)

**Comment by l89669** [comment]
正在搭建皮肤站中。。。
希望阿里云的虚机不要给我太多坑

**Comment by prinsss** [comment]
你还没用皮肤站就提了这个 issue 啊……

**Comment by l89669** [comment]
是啊，我发现authlib-agent没有前端实现所以才找上的你A.A
阿里云的虚机进坑了，无法完成setup，提示escapeshellarg() has been disabled

**Comment by prinsss** [comment]
因为阿里云把 `escapeshellarg` 函数禁用了，皮肤站需要这个函数，下一个

**Comment by l89669** [comment]
我还是老老实实的用vps吧

**Comment by prinsss** [comment]
Closed. 

关于 Yggdrasil API 插件的问题反馈发邮件或者 QQ。
