### ISSUE TITLE
請給出一個目錄權限的説明可以嗎？

### ISSUE THREAD

**Issue by ghost** [printempw/blessing-skin-server#70]
我看這個不錯呢，但是直接從wget到GitHub Release的zip檔案，然後unzip之後，直接訪問就會報500，我嘗試chmod -R 777 *之後就可以咯，但是755和775都是不可以的。基於數據保險的考慮，任何配置文檔都可以從任何幾個網路計算機下載。我嘗試把[/storage][/resourecs]幾個檔案夾授予777權限並-R，其它文檔均爲755，這樣就可以解決了。
請改進讀取機制，或是嘗試其它壓縮方式

**Comment by dz-paji** [comment]
Taiwan NO.1？

在 2017年6月27日，下午1:22，shiye <notifications@github.com<mailto:notifications@github.com>> 写道：


我看這個不錯呢，但是直接從wget到GitHub Release的zip檔案，然後unzip之後，直接訪問就會報500，我嘗試chmod -R 777 *之後就可以咯，但是755和775都是不可以的。基於數據保險的考慮，任何配置文檔都可以從任何幾個網路計算機下載。我嘗試把[/storage][/resourecs]幾個檔案夾授予777權限並-R，其它文檔均爲755，這樣就可以解決了。
請改進讀取機制，或是嘗試其它壓縮方式

**Comment by prinsss** [comment]
懒得去切换，下面用的简体中文，抱歉。

提 issue 前请先查阅 GitHub Wiki 中的「常见问题」页面，那个 500 是因为 php-fpm 没有权限读取 PHP 源码文件导致的。

解决方法也很简单，并不需要暴力 777，只需在皮肤站目录下执行 `chown -R www ./` 即可（www 改成你用来运行 web server 的用户）。

**Comment by prinsss** [comment]
咦？仔细看了你的问题后，发现我上述发言有些不妥。只需要给予 `/storage` 与 `/resources` 目录的写权限即可了吗？那可能是我的测试还不够完善，之后有时间我去弄清楚到底是什么原因导致的 500。

**Comment by ghost** [comment]
為何要這樣急切呢？
我們經過測驗，發現了更多問題。
首先，我們最開始發現問題是有500狀態標識，經過初步的授權後，可以安裝了。
詳細步驟:/resources與/storage兩個檔案夾權限為0777，其檔案夾和檔案為0755，所有的文件來自GitHub Release，屬於root用戶與root組織，Apache2執行用戶為www-data，為獨立的服務器
在解決了安裝的疑難之後，隨即發出了issue
接著進行了初步測試，發現插件市場(Unofficial)不能工作，並且將來源由一個.cf更換成gplane.win，之後仍不能工作，發現是plugins的目錄權限問題，設置0777後均正常工作
測試註冊，登錄，簽章，上載工作正常
目前的幾個問題:一，可以獨立一個php頁面安裝，使用類似.lock文件畫上標記
二，看到resource/lang的裡面有翻譯文檔，可以基於此製作tc翻譯嗎？
三，HP的bg來自CW，能突出一下版權嗎？

**Comment by prinsss** [comment]
感谢你的反馈 :)

1. 原来的版本就是使用独立的 PHP 页面来运行安装程序的，但是考虑到程序耦合等原因，遂将安装程序纳入程序框架内；而且为何不能直接将所有文件的所有者从 root 改为 www-data 呢？
2. 可以，在 `resources/lang` 下创建语言文件夹后请在 `config/locales.php` 中声明语言信息，也欢迎你提交 Pull Request；
3. 默认背景图确实是来自 CthuWork，不过在程序正式发布之前我就已经询问图片作者获取授权了 :)

**Comment by prinsss** [comment]
我在程序启动时添加了对特定目录的写权限检查，现在就算没有对 `storage`、`resources`、`plugins` 目录的写权限也不会直接甩一脸 500 了 :D https://github.com/printempw/blessing-skin-server/commit/4adc6adb956d50f1eaf70ba0f24ecb51f1e85fb6

![screenshot](https://img.blessing.studio/images/2017/06/30/snipaste_20170630_111745.png)
