### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by MlgmXyysd** [printempw/blessing-skin-server#71]
/setup目录不存在，release最新版本

**Comment by dz-paji** [comment]
伪静态配置好了吗？

在 2017年7月1日，下午4:10，Yuze Wu <notifications@github.com<mailto:notifications@github.com>> 写道：


/setup目录不存在，release最新版本

**Comment by prinsss** [comment]
+1，请确认重写规则已正确配置。

**Comment by MlgmXyysd** [comment]
location ~ \.php($|/) {
            set $script $uri;
            set $path_info "";
    
            if ($uri ~ "^(.+.php)(/.+)") {
                set $script $1;
                set $path_info $2;
            }
            
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
这样会报错
于是我就这样        location ~ \.php($|/) {
            set $script $uri;
            set $path_info """
    try_files $uri $uri/ /index.php?$query_string;
            if ($uri ~ "^(.+.php)(/.+)") {
                set $script $1;
                set $path_info $2;
            }
}

**Comment by MlgmXyysd** [comment]
set $path_info "";

**Comment by prinsss** [comment]
就应该是：

```
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
```

请贴出你的完整配置，你可能其他地方配置出错了。

**Comment by MlgmXyysd** [comment]
http://meowcat-1251840916.costj.myqcloud.com/Screenshot_2017-07-01-19-57-15.png
这是整个的截图

**Comment by prinsss** [comment]
你复制错位置了，请把 `location /` 复制到与 `location ~ \.php($|/) {` **同级** 的位置

**Comment by MlgmXyysd** [comment]
额，不是很懂，给个事例

```
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    keepalive_timeout 65;
    sendfile on;
    default_type application/octet-stream;
    root meowcat/center;
    index index.html index.htm index.php;

    server {
        listen 80 default;
        server_name localhost;

        location ~ \.php($|/) {
            set $script $uri;
            set $path_info "";
    
            if ($uri ~ "^(.+.php)(/.+)") {
                set $script $1;
                set $path_info $2;
            }
            
location / {
    try_files $uri $uri/ /index.php?$query_string;
}

# Protect .env file
location ~ /\.env {
    deny all;
}
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$script;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_NAME $script;
            fastcgi_param PATH_INFO $path_info;
        }
    }
}
```

**Comment by MlgmXyysd** [comment]
worker_processes 1;
events {
    worker_connections 1024;
}
http {
    include mime.types;
    keepalive_timeout 65;
    sendfile on;
    default_type application/octet-stream;
    root meowcat/center;
    index index.html index.htm index.php;
    server {
        listen 80 default;
        server_name localhost;
        location ~ \.php($|/) {
            set $script $uri;
            set $path_info "";
            if ($uri ~ "^(.+.php)(/.+)") {
                set $script $1;
                set $path_info $2;
            }
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
location ~ /\.env {
    deny all;
}
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$script;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_NAME $script;
            fastcgi_param PATH_INFO $path_info;
        }
    }
}

**Comment by prinsss** [comment]
```
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    keepalive_timeout 65;
    sendfile on;
    default_type application/octet-stream;
    root meowcat/center;
    index index.html index.htm index.php;

    server {
        listen 80 default;
        server_name localhost;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Protect .env file
        location ~ /\.env {
            deny all;
        }

        location ~ \.php($|/) {
            set $script $uri;
            set $path_info "";
    
            if ($uri ~ "^(.+.php)(/.+)") {
                set $script $1;
                set $path_info $2;
            }
            
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$script;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_NAME $script;
            fastcgi_param PATH_INFO $path_info;
        }
    }
}
```

**Comment by prinsss** [comment]
请正确缩进，谢谢。

**Comment by MlgmXyysd** [comment]
谢谢可以了
