### ISSUE TITLE
关于插件的问题

### ISSUE THREAD

**Issue by 90uncle** [printempw/blessing-skin-server#72]
你好，看了你的插件的写法，非常喜欢。可是对于插件的具体实现却没有。
对于如何写插件，如果在核心代码中部署钩子，没想明天，希望能够提供插件实现demo。
3Q，2752792803@qq.com

**Comment by prinsss** [comment]
示例插件在这里：
https://coding.net/u/printempw/p/blessing-skin-plugins/git/tree/master/example-plugin

我以前也写过一篇关于插件实现的博客文章，有兴趣可以去我博客 blessing.studio 搜索一下

**Comment by dz-paji** [comment]
我记得GPlane dalao有对BS插件的文案进行补充。你可以去Git搜搜。

Sent from my Windows 10 phone

**Comment by g-plane** [comment]
WIP: https://github.com/g-plane/blessing-skin-plugin-docs
