### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by DomRR** [printempw/blessing-skin-server#73]
报错
No vendor folder found. Have you installed the dependencies with composer?

**Comment by prinsss** [comment]
请问你能看完一遍 README 里的安装说明再来提问吗？谢谢你。

这不是报错，是我在提示你去用 composer 安装依赖，你不去好好读一遍那句话我也很无奈。我估计你是直接下载了源码才会这样，如果你不知道怎样使用 composer 安装依赖以及编译前端文件，请在 GitHub releases 或百度云网盘中下载下载预编译好的发布版。

**Comment by DomRR** [comment]
十分抱歉，没有看清说明，问题已解决，感谢_(:зゝ∠)_
