### ISSUE TITLE
一些bug问题

### ISSUE THREAD

**Issue by suoyukii** [printempw/blessing-skin-server#74]
1、角色管理没有删除披风
2、我的衣柜删除材质和披风没有恢复积分

**Comment by g-plane** [comment]
第一点的「角色管理」是「用户中心」的还是「管理面板」的？
第二点已修复了，请耐心等待新版本。

**Comment by suoyukii** [comment]
管理面板 > 角色管理 > 操作
只有删除角色和删除材质
没有删除披风

**Comment by g-plane** [comment]
在下个版本中，点击「更改材质」，然后 PID 填0，就可以删除。

**Comment by prinsss** [comment]
已记录

**Comment by suoyukii** [comment]
评论区挂了

**Comment by dz-paji** [comment]
检查一下你的配置是不是出错了

**Comment by prinsss** [comment]
@HaeDon 请提供更详细的信息，我无法从一句「评论区挂了」得到任何有用的信息，谢谢。

**Comment by suoyukii** [comment]
Google浏览器没显示评论区
360极速浏览器也没显示，兼容模式一样

**Comment by suoyukii** [comment]
Edge浏览器也是

**Comment by prinsss** [comment]
哦，你说演示站啊

正常，多说关闭服务了，我还没去换新的评论框
