### ISSUE TITLE
请求添加一个新功能

### ISSUE THREAD

**Issue by suoyukii** [printempw/blessing-skin-server#75]
最近有人在皮肤站上传黄色皮肤和披风
建议添加个举报功能

**Comment by suoyukii** [comment]
两个举报
一个举报皮肤/披风
另一个举报上传者

**Comment by dz-paji** [comment]
没必要举报两个吧？一起举报不行吗？

**Comment by prinsss** [comment]
我认为只需「举报材质」即可，管理员可根据举报记录，加上被举报材质的上传者其他皮肤决定是否封禁上传者。

你觉得呢？

**Comment by prinsss** [comment]
「举报材质」插件已经发布，适用于 Blessing Skin v3.2.1 及以上。

源码：https://coding.net/u/printempw/p/blessing-skin-plugins/git/tree/master/report-texture
打包下载（解压放入 `plugins` 目录并在后台启用）：https://coding.net/u/printempw/p/blessing-skin-plugins/git/blob/master/dist/report-texture_v1.0.zip

欢迎反馈问题。

![1](https://i.loli.net/2017/07/30/597d7e8a7775e.png)
![2](https://i.loli.net/2017/07/30/597d7e8a79364.png)
