### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by l89669** [printempw/blessing-skin-server#78]

**Comment by prinsss** [comment]
这个 BUG 已经修复过了，请更新至最新版 v3.3。

https://github.com/printempw/blessing-skin-server/releases/tag/v3.3

**Comment by l89669** [comment]
只有超级管理员才会出错
登录后进入用户中心就报错了

**Comment by l89669** [comment]
然而就是最新版。。。 @printempw

**Comment by l89669** [comment]
啊是我搞错了。。。我更新一下

**Comment by l89669** [comment]
@printempw 麻烦大大了，请问一下更新要怎么更新呢？覆盖还是全删除重新配置？

**Comment by prinsss** [comment]
直接全部覆盖就行了，后台也可以直接一键更新。

更新之后记得把 `/storage/frameword/cache/views` 下的缓存文件清空，并且清除浏览器 & CDN 缓存，否则可能出现问题。

**Comment by l89669** [comment]
好的，灰常感谢

**Comment by l89669** [comment]
升级后部分文本不显示中文，怎么解决？ @printempw 
![img_0714](https://user-images.githubusercontent.com/12078899/28772671-6fd56e92-7619-11e7-8ca8-ec1bd2259b24.PNG)

**Comment by prinsss** [comment]
清除浏览器缓存
清除浏览器缓存

你要我说多少遍？

![snipaste_20170731_175542.png](https://i.loli.net/2017/07/31/597efef80984d.png)

**Comment by l89669** [comment]
抱歉。。。(被手机safari坑了。。。)
