### ISSUE TITLE
皮肤不能选类型是Alex还是Steve了？

### ISSUE THREAD

**Issue by tjsky** [printempw/blessing-skin-server#79]
原来的皮肤站材质类型是，三选一

皮肤（Steve）、皮肤（Alex）、披风

![原来站截图](http://ww1.sinaimg.cn/large/7dd4b1bbly1fi3flhq2lij211y0lc0vy.jpg)

现在变成了二选一

皮肤、披风

![现在Blessing Skin站截图](http://ww3.sinaimg.cn/large/7dd4b1bbly1fi3fpggzdaj20rk0fpdh1.jpg)

默认皮肤就是steve，还没法改，导致Alex的皮肤完全没法上传了。

系统win7SP1 浏览器Firefox52和IE11

望作者大大帮忙看看，是哪里出了问题。

----------------------

刚才看了下网页代码，实际上代码有写这部分，但是CCS被设置为
`#skin-type{display: none;}`
纯IE浏览器下应该不存在广告拦截插件，所以怀疑是服务器端做的修改，等我去看下代码

---------------------
我想知道为什么源码里屏蔽了这个选择模块
位于blob/master/resources/views/skinlib/upload.tpl第47行
```
<div class="col-xs-8">
  <select class="form-control" id="skin-type" style="display: none;">
    <option value="steve">{{ trans('skinlib.filter.steve-model') }}</option>
    <option value="alex">{{ trans('skinlib.filter.alex-model') }}</option>
  </select>
</div>
```
从Commits里看，在去年8月份这部分代码被改后，从有这段代码开始，这个none一直在。。
有点晕，难道是故意为之的？总不能都一年了我是第一个提出这个问题的吧。

**Comment by prinsss** [comment]
你应该用的是最新的 v3.3 版本吧？我看了一下，这是个 BUG，本来模型选择的 select 会在切换 皮肤/披风 时自动出现的（如下图），可能是 v3.3 重构 JavaScript 文件时的疏忽导致的，v3.2.1 版本不受影响。

![Screenshot_2017-08-01-01-40-42-025_com.android.chrome.png](https://i.loli.net/2017/08/01/597f6c7a2babe.png)

我将会尽早解决此问题，感谢你的反馈！

**Comment by prinsss** [comment]
临时解决方法，后台「个性化 > 自定义 CSS」中添加如下内容：

```css
#skin-type {
    display: initial !important;
}
```

**Comment by tjsky** [comment]
@printempw 恩，谢谢，昨晚发现问题出在那里后，已经自行解决啦。直接改了upload.tpl

**Comment by suoyukii** [comment]
@printempw 不支持中文昵称

**Comment by prinsss** [comment]
@HaeDon 后台有设置，请自行开启「允许中文角色名」，谢谢。

**Comment by prinsss** [comment]
已修复

https://github.com/printempw/blessing-skin-server/commit/0a201a6c22b487a2a941e478eec7a952d93055e1
