### ISSUE TITLE
首页分辨率自适应有问题，有的时候第一屏会出现滚动条

### ISSUE THREAD

**Issue by l89669** [printempw/blessing-skin-server#80]

**Comment by prinsss** [comment]
首页本来不就是有滚动条的吗？

你说的哪里的首页？请提供截图，谢谢。

**Comment by l89669** [comment]
![image](https://user-images.githubusercontent.com/12078899/28826290-32a2ead4-76fc-11e7-8c03-bef4ad3dbe2c.png)

**Comment by prinsss** [comment]
我这从来没出现过这种情况，我明天尝试一下能否复现。

你 F12 控制台中有什么报错吗？

**Comment by l89669** [comment]
没有报错。。。
我也不大会看，反正没有红色和黄色的东西

**Comment by l89669** [comment]
顺便。这情况在桌面和移动端都有出现，桌面屏幕是4k，缩放至屏幕面积的四分之一后出现，移动端是ip7，横屏后出现

**Comment by l89669** [comment]
![img_0725](https://user-images.githubusercontent.com/12078899/28827318-c0ed69e2-76ff-11e7-876c-00fa201e2a6c.PNG)

**Comment by prinsss** [comment]
我看了一下，成功复现，主要是在网页高度过小的时候出现。

那你觉得应该改成什么样呢？

**Comment by l89669** [comment]
改成什么样需要看页面整体风格，不过肯定不能让页面出现双层滚动条，也不能让按钮显示不全影响美观
我觉得可以让这个框架的高度固定为一个固定数值比如图片的高度，只让宽度和排版变化就可以了

**Comment by dz-paji** [comment]
欢迎PR

在 2017年8月1日，下午10:04，l89669 <notifications@github.com<mailto:notifications@github.com>> 写道：


改成什么样需要看页面整体风格，不过肯定不能让页面出现双层滚动条，也不能让按钮显示不全影响美观
我觉得可以让这个框架的高度固定为一个固定数值比如图片的高度，只让宽度和排版变化就可以了

**Comment by l89669** [comment]
我也很想PR但是并不懂js和php

**Comment by suoyukii** [comment]
@printempw 不支持中文游戏账号
http://skin.xyzmc.net/user/player

**Comment by prinsss** [comment]
@HaeDon

**在 后台 站点配置 里 开启 允许中文角色名**

你到底要我说几遍？

**Comment by suoyukii** [comment]
@printempw 没看到啊

**Comment by dz-paji** [comment]
![image](https://user-images.githubusercontent.com/19299425/28901524-4d88e1d4-782b-11e7-8c69-334723ab194e.png)
@HaeDon
