### ISSUE TITLE
[YggdrasilAPI] io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by l89669** [printempw/blessing-skin-server#81]
```
[10:52:39 INFO]: paihuai_233 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
```

使用的客户端为authlib-agent.jar
服务器为blessing skin server
两玩家在视距内即触发崩溃，表现为强制一方退出服务器

https://github.com/to2mbn/authlib-agent/issues/16

**Comment by prinsss** [comment]
NullPointerException？

是 authlib-agent 那边的问题吧。

**Comment by l89669** [comment]
profiles/minecraft/{uuid}
这个路径，插件返回的数据格式和yggdrasil-backend返回的数据格式不同
@printempw

**Comment by prinsss** [comment]
没有 textures signature 而已（数字签名麻烦，我懒），等 authlib-agent 作者那边怎么说吧。

**Comment by l89669** [comment]
已测试通过Yggdrasil-Backend登陆没有问题，只有blessing插件搭建的yggdrasil服务登陆后才会出错
@printempw

**Comment by l89669** [comment]
59.110.49.168 - - [03/Aug/2017:15:01:14 +0800] "POST /yggdrasil-backend/yggdrasil/authenticate HTTP/1.1" 200 334
59.110.49.168 - - [03/Aug/2017:15:02:33 +0800] "POST /yggdrasil-backend/yggdrasil/authenticate HTTP/1.0" 200 334
59.110.49.168 - - [03/Aug/2017:15:04:10 +0800] "POST /yggdrasil-backend/yggdrasil/refresh HTTP/1.0" 200 334
59.110.49.168 - - [03/Aug/2017:15:05:48 +0800] "POST /yggdrasil-backend/yggdrasil/joinserver HTTP/1.0" 204 -
59.110.49.168 - - [03/Aug/2017:15:05:49 +0800] "GET /yggdrasil-backend/yggdrasil/hasjoinserver?serverId=373cbb1b1256df6dd7f9ab7a288b325519d42953&username=paihuai_299 HTTP/1.0" 200 651
59.110.49.168 - - [03/Aug/2017:15:05:50 +0800] "GET /yggdrasil-backend/yggdrasil/profiles/minecraft/e00d5b8af5474deb870d1fdc7b7ab2b1?unsigned=true HTTP/1.0" 200 651
59.110.49.168 - - [03/Aug/2017:15:06:17 +0800] "POST /yggdrasil-backend/yggdrasil/authenticate HTTP/1.0" 200 334
59.110.49.168 - - [03/Aug/2017:15:06:57 +0800] "POST /yggdrasil-backend/yggdrasil/joinserver HTTP/1.0" 204 -
59.110.49.168 - - [03/Aug/2017:15:06:58 +0800] "GET /yggdrasil-backend/yggdrasil/hasjoinserver?serverId=39cfe811f150e86e150777230861ab5cfcc20135&username=paihuai_255 HTTP/1.0" 200 651
59.110.49.168 - - [03/Aug/2017:15:06:59 +0800] "GET /yggdrasil-backend/yggdrasil/profiles/minecraft/318248fc38b2437e818f54741728f17d?unsigned=true HTTP/1.0" 200 651

**Comment by l89669** [comment]
为了处理bug，我决定开放我网站搭建好的两个后端供大大调戏 @printempw 
yggdrasil-backend的后端是auth.summermc.cc/
yggdrasilapi的后端是summermc.cc/api/yggdrasil/

**Comment by l89669** [comment]
{"timestamp":1501745589711,"profileId":"4b3bb615383b41d38b4e73b6209327a2","profileName":"paihuai","textures":[]} //blessing

{"profileName":"paihuai","textures":{},"profileId":"0d14e042-d3d1-4bcc-a2bb-e9aae05757a3","isPublic":true,"timestamp":1501745631139} //authlib

显然是textures字段的格式错了。。。

**Comment by prinsss** [comment]
Yggdrasil API 插件已升级至 v1.1

https://coding.net/u/printempw/p/blessing-skin-plugins/git/tree/master/yggdrasil-api

**Comment by yushijinhun** [comment]
API`/yggdrasil/profiles/minecraft/:uuid`在指定有`unsigned=false`的query时，应当对返回的properties进行数字签名。此外数字签名应当对properties中所有节点进行，而不是只对第`[0]`个。

**Comment by prinsss** [comment]
@yushijinhun 当未指定 `unsigned=false` 时可否不返回 properties 的数字签名？

**Comment by l89669** [comment]
@yushijinhun 指定unsigned=true仍然会返回数字签名

**Comment by prinsss** [comment]
我看 Mojang 的 API 在未指定 `unsigned` Query String 或是 `unsigned=true` 时都不会返回数字签名，只有在指定 `unsigned=false` 时才会返回数字签名：https://sessionserver.mojang.com/session/minecraft/profile/550743071ff44ec8b356e985cf24fd63?unsigned=true

针对 authlib-agent 开发的第三方 Yggdrasil API，是否也可以采用同样的机制呢？

**Comment by yushijinhun** [comment]
@printempw 就是这样，但是我的后端实现的时候偷懒，就始终返回签名了。

**Comment by l89669** [comment]
但是为什么不返回签名会导致崩溃呢？
明明请求地址带unsigned=true

**Comment by prinsss** [comment]
@yushijinhun 不过正如本 issue 所述，似乎 authlib-agent 在服务端未返回 `signature` 时会触发 `NullPointerException`？查看请求日志时，authlib-agent 发出的请求并未指定 `unsigned=false`。

当我修改后端为始终返回 signature 后不会触发异常。

**Comment by l89669** [comment]
感觉不是agent的问题，更可能是mojang就没实现不带签名的功能

**Comment by yushijinhun** [comment]
这个我也不太清楚。不过始终返回数字签名并不会带来什么副作用，所以暂时就一直返回好了。
我现在在外面旅游，需要过几天回家之后再研究。

**Comment by yushijinhun** [comment]
可以通过yggdrasil-backend的Manager API将签名密钥删除，这样就不会返回数字签名，再测试是否会崩溃。

**Comment by prinsss** [comment]
Yggdrasil API 插件已升级至 v1.1.1，目前的逻辑是：

> 如果插件根目录下存在 `key.pem` 文件，则始终返回数据签名；如果文件不存在，则不返回数据签名；如果私钥文件不存在且指定了 `unsigned=false`，则抛出异常。

@yushijinhun 感谢你的指出

https://coding.net/u/printempw/p/blessing-skin-plugins/git/tree/master/yggdrasil-api

**Comment by yushijinhun** [comment]
我有一篇介绍这个签名公钥的文章，在[这里](https://github.com/to2mbn/authlib-injector/wiki/%E7%AD%BE%E5%90%8D%E5%AF%86%E9%92%A5%E5%AF%B9)。

简言之，客户端通过两种途径获取材质信息：
 1. 直接请求Mojang
 2. 从MC服务端获取

前者对应角色查询的API，而后者对应`hasJoinedServer`这个API。
对于MC客户端，从Mojang获取到的信息都是可信的，因此第一种途径不需要数字签名。
但是第二种途径就存在材质信息被服务端恶意篡改的可能，因此需要在`hasJoinedServer`中包含数字签名，然后MC服务端将签名连同材质一起发给客户端。
