### ISSUE TITLE
[YggdrasilAPI] return error message on authentication if account has no player

### ISSUE THREAD

**Issue by l89669** [printempw/blessing-skin-server#83]
如果玩家账号下未创建任何角色，在api/yggdrasil/authenticate验证时返回一个错误比直接返回信息要好一些

**Comment by prinsss** [comment]
Mojang 对于创建了账号但是没有购买 Minecraft 的玩家 profile 也是这样处理的啊（`availableProfiles` 和 `selectedProfile` 为空，但是会返回 AccessToken）

**Comment by l89669** [comment]
抱歉，光纯post分析数据了，没看启动器的处理逻辑
