### ISSUE TITLE
移除皮肤出现BUG

### ISSUE THREAD

**Issue by suoyukii** [printempw/blessing-skin-server#84]
用户中心→我的衣柜→任意皮肤→从衣柜中移除
404错误

**Comment by prinsss** [comment]
这个 BUG 已经有人报告过了，目前已经修复（ https://github.com/printempw/blessing-skin-server/commit/dd2210a30d56a85ec6ecdf6388a0d53f8f1e4047 ），请等待新版本发布

**Comment by suoyukii** [comment]
@printempw 话说我举报了一堆问题皮肤不处理下吗

**Comment by prinsss** [comment]
演示站？我几万年不上去一次的 (゜゜)

之后有时间我去看看吧

**Comment by HaeDon** [comment]
演示站不是关了吗
演示站关了提示说用这个 [](https://skin.prinzeugen.net/) 了

**Comment by suoyukii** [comment]
演示站不是关了吗
演示站关了提示说用这个 [https://skin.prinzeugen.net/](https://skin.prinzeugen.net/) 了

**Comment by prinsss** [comment]
这个也是演示站啊……和原来那个 IP 访问的数据库之类的都一样的，只是阿里云那台机子快过期了，所以把演示站又搬回来了而已
