### ISSUE TITLE
[WIP]添加用户名，邮箱，角色名的关键字屏蔽

### ISSUE THREAD

**Issue by l89669** [printempw/blessing-skin-server#85]
![qq 20170808153519](https://user-images.githubusercontent.com/12078899/29061168-4ab6fdf6-7c4f-11e7-9f60-a52ce64559fb.png)

**Comment by prinsss** [comment]
为什么不自己去写一个插件呢？我最近忙，没时间加这些乱七八糟的功能。

----------------

插件编写入门：https://github.com/printempw/blessing-skin-server/wiki/Plugins#%E6%88%91%E6%83%B3%E8%A6%81%E5%BC%80%E5%8F%91%E6%8F%92%E4%BB%B6%E6%80%8E%E4%B9%88%E5%85%A5%E9%97%A8

### 思路提示：

1. 监听 `App\Events\PlayerWillBeAdded` 事件；
2. 从事件实例中取出玩家要添加的角色名（ `$event->player_name` ）；
3. 判断该角色名中是否包含你自定义的关键词；
4. 如果没有，不进行任何操作；如果有，立即结束请求并返回错误信息：

```php
json(['errno' => 1, 'msg' => '角色名中不能包含敏感词汇'])->send();
exit;
```

**Comment by l89669** [comment]
Working on
@printempw 大概写完了你能拿去放到插件市场吗？

**Comment by prinsss** [comment]
目前默认的插件市场并不是我在运营的，任何注册用户都可以提交插件。

http://plugin.gplane.win/
