### ISSUE TITLE
我的举报BUG反馈

### ISSUE THREAD

**Issue by suoyukii** [printempw/blessing-skin-server#86]
点击被举报的作者链接出错

例子：[http://skin.dev/skinlib?filter=skin&uploader=10299](http://skin.dev/skinlib?filter=skin&uploader=10299)
正确的地址：[https://skin.prinzeugen.net/skinlib?filter=skin&uploader=10299](https://skin.prinzeugen.net/skinlib?filter=skin&uploader=10299)

**Comment by suoyukii** [comment]
BUG位置：用户中心→我的举报

**Comment by suoyukii** [comment]
话说我举报了一堆有问题的皮肤和披风都没人管的，一直都显示“正在处理”，到底要处理到何年何月呀

**Comment by prinsss** [comment]
已修复

https://github.com/printempw/blessing-skin-plugins/commit/5616464f930a5961776e52384aa7746722b665f3

**Comment by suoyukii** [comment]
@printempw 本来这BUG我想帮你改的结果我找不到网页模版在哪

**Comment by prinsss** [comment]
在插件目录里啊

https://github.com/printempw/blessing-skin-plugins/blob/master/report-texture/views/report.tpl

**Comment by suoyukii** [comment]
我当时不知道在插件里面，我还以没上传
