### ISSUE TITLE
Laravel log files can be access in browser, this can cause severe username&password leak

### ISSUE THREAD

**Issue by l89669** [printempw/blessing-skin-server#87]
./storage/logs/laravel.log可以被直接访问，其中包含用户名密码和其他站点敏感信息
建议添加教程将它设置为无法访问并修改htaccess文件

**Comment by prinsss** [comment]
嗯……一般来说我是不会在日志里记录用户密码之类的信息的

如果你看到了，那可能是「数据对接」或者是「Yggdrasil API」插件记录的日志，其中数据对接插件我提供了关闭日志记录的选项，Yggdrasil API 插件目前还没有（之后会更新）。

**Comment by prinsss** [comment]
Yggdrasil API 插件以更新至 v1.1.4，默认不记录详细日志。

https://github.com/printempw/blessing-skin-plugins/commit/11b38aca9170f08a8b3fd8f88b947550f09b56ad
