### ISSUE TITLE
高分辨率下「我的衣柜」中衣柜物品没有填满页面

### ISSUE THREAD

**Issue by suoyukii** [printempw/blessing-skin-server#89]
我是不是没权限修改代码
我想调下[https://skin.prinzeugen.net/user/closet](https://skin.prinzeugen.net/user/closet)这个页面
对1080P的美化问题
默认显示6个不填满强老犯强迫症

前端的JS框架用的是哪个
还得在识别下分辨率
然后get请求补上一个width参数=1080就可以用了

**Comment by g-plane** [comment]
怎样的不填满？发个图看看？

**Comment by g-plane** [comment]
复现出来了
![sp20170815_220800](https://user-images.githubusercontent.com/17216317/29319322-3be94204-8206-11e7-9a0a-4c383659c45f.png)
衣柜这里的确没有做到响应式，但往 GET 参数里添加屏幕信息也许不是灵活的做法，例如在其它的分辨率下，又可能是别的情况。

**Comment by suoyukii** [comment]
@g-plane CSS改下用计算的方式获取margin-left的边距
不然不美观呀

**Comment by suoyukii** [comment]
![qq 20170816071340](https://user-images.githubusercontent.com/16282726/29340605-74a0da2a-8252-11e7-9846-891a537560a3.jpg)

**Comment by g-plane** [comment]
上面那张图好像不是仅仅修改 CSS 后的效果？

**Comment by suoyukii** [comment]
@g-plane 没错，我js代码改了下，获取的最后一个皮肤的div容器复制了两次接后面了

**Comment by g-plane** [comment]
相比于把 width 参数放入 GET 请求中，我觉得用 JS 判断屏幕大小然后将每页显示的皮肤数放入请求体中会更好些。

**Comment by suoyukii** [comment]
@g-plane 就是这样啊，width参数就是通过js获取屏幕大小的宽，然后通过get请求发过去的

**Comment by g-plane** [comment]
不是，你可能没完全理解我的意思。我的意思是屏幕大小是不会被发送的。

**Comment by HaeDon** [comment]
一次返回8个皮肤，判断屏幕大小取个数填充？

**Comment by suoyukii** [comment]
直接要求返回的皮肤个数

**Comment by suoyukii** [comment]
还不是要一个发送一个GET参数

**Comment by g-plane** [comment]
嗯，差不多是这样。

**Comment by g-plane** [comment]
但从解耦的角度来讲，你觉得发送宽度好些还是发送返回的个数好些？这个很明显的吧？

**Comment by suoyukii** [comment]
随便你反正结果是一样的

**Comment by g-plane** [comment]
过段时间我用插件实现一下吧，到时你安装这个插件就可以了。

**Comment by g-plane** [comment]
@HaeDon 请问你是一直都是使用演示站还是有自己的皮肤站？

**Comment by suoyukii** [comment]
@g-plane 演示站

**Comment by g-plane** [comment]
那抱歉了，这个问题需要等作者来解决

**Comment by suoyukii** [comment]
@g-plane 他干嘛不一开始就考虑清楚

**Comment by prinsss** [comment]
@HaeDon 哪有一个项目从最开始就是尽善尽美的呢？

**Comment by suoyukii** [comment]
@printempw 有，公司一直强调自适应兼容所有浏览器和一些常见的分辨率，所以老手的很自觉

**Comment by prinsss** [comment]
@HeaDon 很可惜，我并不是大公司里的老手开发者，只是一介编写开源软件练手的新人而已 :)

另，单纯的分辨率适配与响应式我自然是最开始就考虑了。

**Comment by suoyukii** [comment]
@g-plane @printempw 这个功能都提出多久了 还没做吗

**Comment by suoyukii** [comment]
下面按高度来算的
1440：24个
1080：12个
900：9个
720：6个
