### ISSUE TITLE
这什么鬼

### ISSUE THREAD

**Issue by MlgmXyysd** [printempw/blessing-skin-server#90]
No vendor folder found. Have you installed the dependencies with composer? 
根目录下未发现 vendor 文件夹，请参照安装说明使用 composer 安装依赖库。
IIS的服务器，config写好了

**Comment by MlgmXyysd** [comment]
好了不用了

**Comment by MlgmXyysd** [comment]
还是不对，刚升级了下php还是提示这

**Comment by g-plane** [comment]
推荐用已构建好的 release 包
https://github.com/printempw/blessing-skin-server/releases
