### ISSUE TITLE
希望加入多背景图随机选择

### ISSUE THREAD

**Issue by tjsky** [printempw/blessing-skin-server#92]
直接自定义CSS修改背景图地址，但是不生效。。
使用代码如下

```
.wrapper{
background-image: url("./images/1.jpg"),url("./images/2.jpg"),url("./images/3.jpg");}
```
自适应的样式会覆盖掉自定义背景图的CSS。

目前只能直接改动
resources/views/index.tpl文件里这一行
`<div class="wrapper" style="background-image: url('{{ option('home_pic_url') }}');">`
直接写死样式。

不知道是我自定义样式写法不对还是怎么了。希望多背景图轮换能被直接内置到代码里。

**Comment by g-plane** [comment]
我觉得作者应该不会把这个功能加入到皮肤站的核心代码里。如果您稍微懂些 PHP，可以考虑自己写个插件；或者您确实有这个需求但自己不会，我也许可以在 [首页样式插件](https://github.com/g-plane/multi-index-style) 中实现这个功能。

**Comment by suoyukii** [comment]
首页轮播有什么用
就先说一张1080P的图片加载要多久
再多几张1080P的图片要加载多久
其次有人整天没事停在首页看个几分钟的吗

**Comment by tjsky** [comment]
@HaeDon @g-plane 
额，可能我的表述有问题，我的意思是：
每次玩家进入皮肤站，会是不同的首页背景。不是定时换图片。
知道CSS3的应该能看懂我上边那个CSS，我的意思是每次进去首页时，背景是3张背景图里的随机一张。

**Comment by g-plane** [comment]
这个很简单，我可以在「首页样式插件」里实现这个功能。

**Comment by g-plane** [comment]
@tjsky 此功能已加入到 [首页样式插件](https://github.com/g-plane/multi-index-style) 的 1.2.0 版本，欢迎使用。
