### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by KJZH001** [printempw/blessing-skin-server#97]
怎么安装啊？
2.4.5缺失config.php
2.4.5网址：http://rcraft.xszz.gq/web/mcsink/
3.3.1解压后提示没有p（哪哈？）文件夹，创建了之后直接转跳到/setup
可是解压的文件里没有setup
（注：.env改过了）
网址：http://rcraft.xszz.gq/web/mcsink3.3.1/
求解释，是我哪里搞错了了吗？
php7.x应该是没啥问题的。。。
cpanel主机。。。
麻烦安装说明详细点。。。。

**Comment by dz-paji** [comment]
请使用发行版本
安装到子目录需要更改伪静态
脑子是个好东西，但可惜不是人人都有

Sent from my iPhone

On 9 Sep 2017, at 11:39 AM, KJZH001 <notifications@github.com<mailto:notifications@github.com>> wrote:


怎么安装啊？
2.4.5缺失config.php
2.4.5网址：http://rcraft.xszz.gq/web/mcsink/
3.3.1解压后提示没有p（哪哈？）文件夹，创建了之后直接转跳到/setup
可是解压的文件里没有setup
（注：.env改过了）
网址：http://rcraft.xszz.gq/web/mcsink3.3.1/
求解释，是我哪里搞错了了吗？
php7.x应该是没啥问题的。。。
cpanel主机。。。
麻烦安装说明详细点。。。。

**Comment by tnqzh123** [comment]
我想骂一句 mdzz，因为你的问题在 readme 中都有说明。
v2 https://github.com/printempw/blessing-skin-server/tree/v2#快速使用
v3 https://github.com/printempw/blessing-skin-server/tree/master#快速使用
眼睛和脑子是好东西，可惜不是人人都有。
对于没有 /setup 目录的问题，你知道什么是伪静态吗。

**Comment by KJZH001** [comment]
。。。。才刚入php的大坑，伪静态真心不知道怎么弄。。。

readme我看过不下于3次，可还是不知道怎么解决。。。。

**Comment by KJZH001** [comment]
解决了。。。怎么删帖。。。。TAT

**Comment by KJZH001** [comment]
为什么。。。。
escapeshellarg（）已被禁用出于安全原因

**Comment by tnqzh123** [comment]
这看字面意思还不明白？
你的虚拟主机商禁用了 escapeshellarg 函数，自行联系服务商解决。
