### ISSUE TITLE
插件开发 & 协议问题

### ISSUE THREAD

**Issue by g-plane** [printempw/blessing-skin-server#98]
皮肤站源码目前是基于 GPL v3。在这种情况下，插件开发是否必须并且也要以 GPL v3 开源？因为插件会不可避免地调用皮肤站提供的各种接口。或者说，是否需要更换协议以允许插件闭源？

**Comment by PonyPC** [comment]
I think so.

**Comment by prinsss** [comment]
到时候我在版权声明那边加个例外情况「为 Blessing Skin 皮肤站程序开发的插件不强制要求开放源代码」应该就行了🤔

我也不愿意强制让插件作者开源，直接声明特例情况也是可以的吧？毕竟规矩是死的，人是活的嘛
